//! Integration coverage for CockroachDB's PostgreSQL-wire compatibility
//! surface.  These tests use a real CockroachDB server because catalog gaps
//! and DDL transaction behavior cannot be established from synthetic models.
//!
//! Set DPM_TEST_COCKROACH_DATABASE_URL to an admin URL whose role can CREATE
//! DATABASE (scripts/test-cockroach.sh starts an isolated single-node server).

use dpm::apply::apply_script;
use dpm::diff::diff;
use dpm::emit::{emit, EmitOptions};
use dpm::introspect::{introspect_url, IntrospectOptions};
use dpm::model::DatabaseFlavor;
use dpm::source::{resolve, ResolveContext, ShadowDb, SideSpec};
use dpm::verify::{verify, VerifyParams};
use std::process::Command;

fn admin_url() -> Option<String> {
    match std::env::var("DPM_TEST_COCKROACH_DATABASE_URL") {
        Ok(value) if !value.is_empty() => Some(value),
        _ => {
            eprintln!(
                "skipping: DPM_TEST_COCKROACH_DATABASE_URL not set \
                 (run scripts/test-cockroach.sh)"
            );
            None
        }
    }
}

const DESIRED_SCHEMA: &str = r#"
CREATE SCHEMA app;
CREATE TYPE public.order_state AS ENUM ('pending', 'paid', 'shipped');
CREATE SEQUENCE public.invoice_number START 100 INCREMENT 5;

CREATE TABLE public.accounts (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  email STRING NOT NULL,
  state public.order_state NOT NULL DEFAULT 'pending',
  active BOOL NOT NULL DEFAULT true,
  credit DECIMAL(12,2) NOT NULL DEFAULT 0,
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_email_key UNIQUE (email),
  CONSTRAINT accounts_credit_check CHECK (credit >= 0)
);
CREATE INDEX accounts_active_idx ON public.accounts (active);

CREATE TABLE app.orders (
  id INT NOT NULL DEFAULT unique_rowid(),
  account_id UUID NOT NULL,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_account_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);

CREATE VIEW public.active_accounts AS
  SELECT id, email FROM public.accounts WHERE active;
"#;

const DIVERGENT_SCHEMA: &str = r#"
CREATE TABLE public.accounts (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  email STRING NOT NULL,
  legacy_note STRING,
  CONSTRAINT accounts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stale_data (id INT PRIMARY KEY, note STRING);
"#;

const CHANGED_INDEX_AND_VIEW_SOURCE: &str = r#"
CREATE TABLE public.items (
  id INT PRIMARY KEY,
  label STRING NOT NULL,
  score INT NOT NULL DEFAULT 0
);
CREATE INDEX items_search_idx ON public.items (lower(label)) WHERE score > 0;
CREATE VIEW public.item_search AS
  SELECT id, lower(label) AS normalized_label FROM public.items WHERE score > 0;
"#;

const CHANGED_INDEX_AND_VIEW_TARGET: &str = r#"
CREATE TABLE public.items (
  id INT PRIMARY KEY,
  label STRING NOT NULL,
  score INT NOT NULL DEFAULT 0
);
CREATE INDEX items_search_idx ON public.items (score);
CREATE VIEW public.item_search AS SELECT id, label AS normalized_label FROM public.items;
"#;

const IDENTITY_AND_COMPUTED_SOURCE: &str = r#"
CREATE TABLE public.metrics (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  reading INT NOT NULL,
  doubled INT GENERATED ALWAYS AS (reading * 2) STORED,
  CONSTRAINT metrics_pkey PRIMARY KEY (id)
);
"#;

const IDENTITY_AND_COMPUTED_TARGET: &str = r#"
CREATE TABLE public.metrics (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  reading INT NOT NULL,
  CONSTRAINT metrics_pkey PRIMARY KEY (id)
);
"#;

const RLS_SOURCE: &str = r#"
CREATE TABLE public.documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  visible BOOL NOT NULL DEFAULT false,
  body STRING NOT NULL
);
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY documents_visible ON public.documents FOR SELECT USING (visible);
"#;

const RLS_TARGET: &str = r#"
CREATE TABLE public.documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  visible BOOL NOT NULL DEFAULT false,
  body STRING NOT NULL
);
"#;

const COLUMN_TRANSITION_SOURCE: &str = r#"
CREATE TABLE public.measurements (
  id INT PRIMARY KEY,
  value BIGINT NOT NULL DEFAULT 7,
  note STRING,
  CONSTRAINT measurements_value_check CHECK (value <= 1000)
);
"#;

const COLUMN_TRANSITION_TARGET: &str = r#"
CREATE TABLE public.measurements (
  id INT PRIMARY KEY,
  value SMALLINT DEFAULT 1,
  note STRING NOT NULL DEFAULT 'legacy',
  CONSTRAINT measurements_value_check CHECK (value <= 100)
);
"#;

const ROUTINES_AND_TRIGGERS_SOURCE: &str = r#"
CREATE TABLE public.accounts (
  id INT PRIMARY KEY,
  balance INT NOT NULL,
  touched BOOL NOT NULL DEFAULT false
);
CREATE TABLE public.account_audit (
  account_id INT NOT NULL,
  new_balance INT NOT NULL
);
CREATE FUNCTION public.multiply_values(a INT, b INT) RETURNS INT
  AS 'SELECT a * b' LANGUAGE SQL IMMUTABLE;
CREATE PROCEDURE public.credit_account(account_id INT, amount INT)
  LANGUAGE PLpgSQL AS $$
BEGIN
  UPDATE public.accounts
     SET balance = balance + amount
   WHERE accounts.id = account_id;
END
$$;
CREATE FUNCTION public.audit_account_update() RETURNS TRIGGER AS $$
BEGIN
  NEW.touched := true;
  INSERT INTO public.account_audit(account_id, new_balance)
    VALUES ((NEW).id, (NEW).balance);
  RETURN NEW;
END
$$ LANGUAGE PLpgSQL;
CREATE TRIGGER accounts_audit
  BEFORE UPDATE ON public.accounts
  FOR EACH ROW EXECUTE FUNCTION public.audit_account_update();
"#;

const ROUTINES_AND_TRIGGERS_TARGET: &str = r#"
CREATE TABLE public.accounts (
  id INT PRIMARY KEY,
  balance INT NOT NULL,
  touched BOOL NOT NULL DEFAULT false
);
CREATE TABLE public.account_audit (
  account_id INT NOT NULL,
  new_balance INT NOT NULL
);
CREATE FUNCTION public.multiply_values(a INT, b INT) RETURNS INT
  AS 'SELECT a + b' LANGUAGE SQL IMMUTABLE;
CREATE PROCEDURE public.credit_account(account_id INT, amount INT)
  LANGUAGE PLpgSQL AS $$
BEGIN
  UPDATE public.accounts
     SET balance = balance - amount
   WHERE accounts.id = account_id;
END
$$;
CREATE PROCEDURE public."obsolete account job"()
  LANGUAGE SQL AS 'SELECT 1';
CREATE FUNCTION public.audit_account_update() RETURNS TRIGGER AS $$
BEGIN
  NEW.touched := false;
  RETURN NEW;
END
$$ LANGUAGE PLpgSQL;
CREATE TRIGGER accounts_audit
  BEFORE UPDATE ON public.accounts
  FOR EACH ROW EXECUTE FUNCTION public.audit_account_update();
"#;

const ADVANCED_INDEX_SOURCE: &str = r#"
CREATE TABLE public.search_documents (
  id INT PRIMARY KEY,
  tenant_id INT NOT NULL,
  title STRING NOT NULL,
  payload JSONB NOT NULL,
  active BOOL NOT NULL DEFAULT true
);
CREATE INDEX documents_covering_idx
  ON public.search_documents (tenant_id, title DESC)
  STORING (payload) WHERE active;
CREATE INVERTED INDEX documents_payload_idx
  ON public.search_documents (payload);
CREATE UNIQUE INDEX documents_title_unique_idx
  ON public.search_documents (tenant_id, lower(title)) WHERE active;
"#;

const ADVANCED_INDEX_TARGET: &str = r#"
CREATE TABLE public.search_documents (
  id INT PRIMARY KEY,
  tenant_id INT NOT NULL,
  title STRING NOT NULL,
  payload JSONB NOT NULL,
  active BOOL NOT NULL DEFAULT true
);
CREATE INDEX documents_covering_idx
  ON public.search_documents (tenant_id, title);
CREATE INDEX documents_payload_idx
  ON public.search_documents (tenant_id);
CREATE INDEX documents_obsolete_idx
  ON public.search_documents (active);
CREATE UNIQUE INDEX documents_obsolete_unique_idx
  ON public.search_documents (title);
"#;

async fn fresh_db(admin: &str) -> ShadowDb {
    ShadowDb::create(admin, false)
        .await
        .expect("create CockroachDB test database")
}

async fn migrate_and_assert_converges(
    admin: &str,
    source_sql: &str,
    target_sql: &str,
    label: &str,
) -> (ShadowDb, ShadowDb, String) {
    let source_db = fresh_db(admin).await;
    let target_db = fresh_db(admin).await;
    source_db
        .apply_sql(source_sql)
        .await
        .expect("populate desired CockroachDB schema");
    target_db
        .apply_sql(target_sql)
        .await
        .expect("populate current CockroachDB schema");

    let opts = IntrospectOptions::default();
    let source = introspect_url(&source_db.url, &opts)
        .await
        .expect("introspect desired CockroachDB schema");
    let target = introspect_url(&target_db.url, &opts)
        .await
        .expect("introspect current CockroachDB schema");
    assert_eq!(source.database_flavor, DatabaseFlavor::Cockroach);
    assert_eq!(target.database_flavor, DatabaseFlavor::Cockroach);

    let plan = diff(&source, &target);
    let script = emit(
        &plan,
        &EmitOptions {
            allow_destructive: true,
            database_flavor: DatabaseFlavor::Cockroach,
            ..Default::default()
        },
    );
    assert!(script.sql.contains("dialect: CockroachDB"));
    apply_script(&target_db.url, &script.sql)
        .await
        .unwrap_or_else(|error| {
            panic!(
                "[{label}] applying CockroachDB migration failed: {error:#}\n{}",
                script.sql
            )
        });

    let migrated = introspect_url(&target_db.url, &opts)
        .await
        .expect("re-introspect migrated CockroachDB schema");
    let residual = diff(&source, &migrated);
    assert!(
        residual.is_empty(),
        "[{label}] CockroachDB migration did not converge:\n{}\n--- migration ---\n{}",
        emit(
            &residual,
            &EmitOptions {
                database_flavor: DatabaseFlavor::Cockroach,
                ..Default::default()
            },
        )
        .sql,
        script.sql
    );

    (source_db, target_db, script.sql)
}

async fn assert_converges(admin: &str, source_sql: &str, target_sql: &str, label: &str) {
    let (source_db, target_db, _) =
        migrate_and_assert_converges(admin, source_sql, target_sql, label).await;
    source_db.drop_db().await;
    target_db.drop_db().await;
}

#[tokio::test]
async fn cockroach_bootstrap_converges() {
    let Some(admin) = admin_url() else { return };
    assert_converges(&admin, DESIRED_SCHEMA, "", "bootstrap").await;
}

#[tokio::test]
async fn cockroach_divergent_schema_converges() {
    let Some(admin) = admin_url() else { return };
    assert_converges(&admin, DESIRED_SCHEMA, DIVERGENT_SCHEMA, "divergent").await;
}

#[tokio::test]
async fn cockroach_deparsers_are_database_independent() {
    let Some(admin) = admin_url() else { return };
    let left = fresh_db(&admin).await;
    let right = fresh_db(&admin).await;
    left.apply_sql(DESIRED_SCHEMA).await.unwrap();
    right.apply_sql(DESIRED_SCHEMA).await.unwrap();

    let opts = IntrospectOptions::default();
    let left_catalog = introspect_url(&left.url, &opts).await.unwrap();
    let right_catalog = introspect_url(&right.url, &opts).await.unwrap();
    let plan = diff(&left_catalog, &right_catalog);
    assert!(
        plan.is_empty(),
        "CockroachDB catalog output must not embed each shadow database name:\n{}",
        emit(
            &plan,
            &EmitOptions {
                database_flavor: DatabaseFlavor::Cockroach,
                ..Default::default()
            },
        )
        .sql
    );

    left.drop_db().await;
    right.drop_db().await;
}

#[tokio::test]
async fn cockroach_cli_apply_converges() {
    let Some(admin) = admin_url() else { return };
    let source_db = fresh_db(&admin).await;
    let target_db = fresh_db(&admin).await;
    source_db.apply_sql(DESIRED_SCHEMA).await.unwrap();
    target_db.apply_sql(DIVERGENT_SCHEMA).await.unwrap();

    let output = Command::new(env!("CARGO_BIN_EXE_dpm"))
        .args([
            "apply",
            "--source",
            &source_db.url,
            "--target",
            &target_db.url,
            "--yes",
            "--allow-destructive",
        ])
        .output()
        .expect("run dpm apply against CockroachDB");
    assert!(
        output.status.success(),
        "dpm apply failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("dialect: CockroachDB"),
        "CLI migration output should identify the selected dialect"
    );

    let opts = IntrospectOptions::default();
    let source = introspect_url(&source_db.url, &opts).await.unwrap();
    let migrated = introspect_url(&target_db.url, &opts).await.unwrap();
    assert!(
        diff(&source, &migrated).is_empty(),
        "dpm CLI apply must converge the CockroachDB target"
    );

    source_db.drop_db().await;
    target_db.drop_db().await;
}

#[tokio::test]
async fn cockroach_cli_dump_diff_verify_and_dialect_guards() {
    let Some(admin) = admin_url() else { return };
    let source_db = fresh_db(&admin).await;
    let target_db = fresh_db(&admin).await;
    source_db.apply_sql(DESIRED_SCHEMA).await.unwrap();
    target_db.apply_sql(DIVERGENT_SCHEMA).await.unwrap();

    let scratch = std::env::temp_dir().join(format!(
        "dpm-cockroach-cli-{}",
        std::process::id()
    ));
    std::fs::create_dir_all(&scratch).unwrap();
    let dump_path = scratch.join("desired.json");
    let dump = Command::new(env!("CARGO_BIN_EXE_dpm"))
        .args(["dump", "--source", &source_db.url, "--out"])
        .arg(&dump_path)
        .output()
        .expect("dump CockroachDB catalog through the CLI");
    assert!(
        dump.status.success(),
        "CockroachDB dump failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&dump.stdout),
        String::from_utf8_lossy(&dump.stderr)
    );
    assert!(dump.stdout.is_empty(), "--out must keep stdout clean");
    let dumped: dpm::model::Catalog =
        serde_json::from_str(&std::fs::read_to_string(&dump_path).unwrap()).unwrap();
    assert_eq!(dumped.database_flavor, DatabaseFlavor::Cockroach);

    let plan = Command::new(env!("CARGO_BIN_EXE_dpm"))
        .args(["diff", "--format", "json", "--fail-on-diff", "--source-json"])
        .arg(&dump_path)
        .args(["--target", &target_db.url])
        .output()
        .expect("diff CockroachDB catalog against a live target");
    assert_eq!(
        plan.status.code(),
        Some(2),
        "stderr:\n{}",
        String::from_utf8_lossy(&plan.stderr)
    );
    let plan_json: serde_json::Value =
        serde_json::from_slice(&plan.stdout).expect("CLI must emit valid JSON");
    assert!(plan_json["summary"]["total"].as_u64().unwrap() > 0);
    assert!(plan_json["sql"]
        .as_str()
        .unwrap()
        .contains("dialect: CockroachDB"));

    let verified = Command::new(env!("CARGO_BIN_EXE_dpm"))
        .args(["verify", "--source-json"])
        .arg(&dump_path)
        .args([
            "--target",
            &target_db.url,
            "--shadow",
            &admin,
            "--allow-destructive-sql",
        ])
        .output()
        .expect("verify CockroachDB migration through the CLI");
    assert!(
        verified.status.success(),
        "CockroachDB verify failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&verified.stdout),
        String::from_utf8_lossy(&verified.stderr)
    );
    assert!(String::from_utf8_lossy(&verified.stderr).contains("VERIFIED"));

    let postgres_dump = scratch.join("postgres.json");
    let postgres_catalog = dpm::model::Catalog {
        database_flavor: DatabaseFlavor::Postgres,
        server_version_num: 160_000,
        ..Default::default()
    };
    std::fs::write(
        &postgres_dump,
        serde_json::to_string_pretty(&postgres_catalog).unwrap(),
    )
    .unwrap();
    let cross_dialect = Command::new(env!("CARGO_BIN_EXE_dpm"))
        .args(["diff", "--source-json"])
        .arg(&postgres_dump)
        .args(["--target", &source_db.url])
        .output()
        .expect("exercise the CLI cross-dialect guard");
    assert_eq!(cross_dialect.status.code(), Some(1));
    let error = String::from_utf8_lossy(&cross_dialect.stderr);
    assert!(error.contains("source is PostgreSQL but target is CockroachDB"), "{error}");

    source_db.drop_db().await;
    target_db.drop_db().await;
}

#[tokio::test]
async fn cockroach_verify_replays_and_proves_convergence() {
    let Some(admin) = admin_url() else { return };
    let source_db = fresh_db(&admin).await;
    let target_db = fresh_db(&admin).await;
    source_db.apply_sql(DESIRED_SCHEMA).await.unwrap();
    target_db.apply_sql(DIVERGENT_SCHEMA).await.unwrap();

    let opts = IntrospectOptions::default();
    let source = introspect_url(&source_db.url, &opts).await.unwrap();
    let target = introspect_url(&target_db.url, &opts).await.unwrap();
    let outcome = verify(VerifyParams {
        source: &source,
        target: &target,
        shadow_server_url: &admin,
        source_url_for_external: None,
        allow_destructive: true,
        external_check: None,
        checks: Default::default(),
        bins: Default::default(),
        keep_shadow: false,
        verbose: false,
        introspect: &opts,
    })
    .await
    .expect("CockroachDB verify should complete");
    assert!(
        outcome.converged,
        "CockroachDB verify residual:\n{:?}\n--- migration ---\n{}",
        outcome.residual_sql, outcome.migration_sql
    );

    source_db.drop_db().await;
    target_db.drop_db().await;
}

#[tokio::test]
async fn cockroach_enum_insertion_converges() {
    let Some(admin) = admin_url() else { return };
    assert_converges(
        &admin,
        "CREATE TYPE public.priority AS ENUM ('low', 'medium', 'high', 'urgent');",
        "CREATE TYPE public.priority AS ENUM ('low', 'high');",
        "enum-insertion",
    )
    .await;
}

#[tokio::test]
async fn cockroach_sequence_alter_converges() {
    let Some(admin) = admin_url() else { return };
    assert_converges(
        &admin,
        "CREATE SEQUENCE public.order_numbers AS BIGINT INCREMENT BY 10 MINVALUE 100 MAXVALUE 999999 START WITH 100 CACHE 5 NO CYCLE;",
        "CREATE SEQUENCE public.order_numbers AS BIGINT INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 START WITH 1 CACHE 1 NO CYCLE;",
        "sequence-alter",
    )
    .await;
}

#[tokio::test]
async fn cockroach_identity_and_computed_columns_converge() {
    let Some(admin) = admin_url() else { return };
    assert_converges(
        &admin,
        IDENTITY_AND_COMPUTED_SOURCE,
        IDENTITY_AND_COMPUTED_TARGET,
        "identity-computed",
    )
    .await;
}

#[tokio::test]
async fn cockroach_changed_index_and_view_converge() {
    let Some(admin) = admin_url() else { return };
    assert_converges(
        &admin,
        CHANGED_INDEX_AND_VIEW_SOURCE,
        CHANGED_INDEX_AND_VIEW_TARGET,
        "changed-index-view",
    )
    .await;
}

#[tokio::test]
async fn cockroach_functions_procedures_and_triggers_converge_and_execute() {
    let Some(admin) = admin_url() else { return };
    let (source_db, target_db, migration) = migrate_and_assert_converges(
        &admin,
        ROUTINES_AND_TRIGGERS_SOURCE,
        ROUTINES_AND_TRIGGERS_TARGET,
        "routines-triggers",
    )
    .await;

    assert!(
        migration.contains("DROP TRIGGER IF EXISTS \"accounts_audit\""),
        "CockroachDB trigger functions must cycle their dependent triggers:\n{migration}"
    );
    assert!(
        migration.contains("CREATE OR REPLACE FUNCTION"),
        "{migration}"
    );
    assert!(
        migration.contains("CREATE OR REPLACE PROCEDURE"),
        "{migration}"
    );
    assert!(
        migration.contains("DROP PROCEDURE IF EXISTS \"public\".\"obsolete account job\"()"),
        "{migration}"
    );

    let mut conn = dpm::introspect::connect(&target_db.url).await.unwrap();
    sqlx::raw_sql(
        "INSERT INTO public.accounts (id, balance) VALUES (1, 10); \
         CALL public.credit_account(1, 5);",
    )
    .execute(&mut conn)
    .await
    .expect("execute migrated CockroachDB procedure and trigger");
    let behavior: (i64, bool, i64, i64) = sqlx::query_as(
        "SELECT a.balance, a.touched, public.multiply_values(3, 4), count(au.account_id)::INT8 \
           FROM public.accounts a \
           LEFT JOIN public.account_audit au ON au.account_id = a.id \
          WHERE a.id = 1 \
          GROUP BY a.balance, a.touched",
    )
    .fetch_one(&mut conn)
    .await
    .unwrap();
    assert_eq!(behavior, (15, true, 12, 1));

    source_db.drop_db().await;
    target_db.drop_db().await;
}

#[tokio::test]
async fn cockroach_overloaded_procedures_keep_their_signatures() {
    let Some(admin) = admin_url() else { return };
    for sql in [
        "CREATE PROCEDURE public.record_value(a INT) LANGUAGE SQL AS 'SELECT a'; \
         CREATE PROCEDURE public.record_value(a STRING) LANGUAGE SQL AS 'SELECT a';",
        "CREATE PROCEDURE public.record_value(a STRING) LANGUAGE SQL AS 'SELECT a'; \
         CREATE PROCEDURE public.record_value(a INT) LANGUAGE SQL AS 'SELECT a';",
    ] {
        let db = fresh_db(&admin).await;
        db.apply_sql(sql).await.unwrap();

        let catalog = introspect_url(&db.url, &IntrospectOptions::default())
            .await
            .unwrap();
        let int_def = &catalog.functions["public.record_value(int8)"].def;
        let text_def = &catalog.functions["public.record_value(text)"].def;
        assert!(int_def.contains("record_value(a INT8)"), "{int_def}");
        assert!(text_def.contains("record_value(a STRING)"), "{text_def}");

        db.drop_db().await;
    }
}

#[tokio::test]
async fn cockroach_routine_options_bootstrap_json_and_teardown() {
    let Some(admin) = admin_url() else { return };
    let schema = r#"
CREATE FUNCTION public.secure_greeting(prefix STRING DEFAULT 'hello')
  RETURNS STRING IMMUTABLE SECURITY DEFINER LANGUAGE SQL
  AS 'SELECT prefix || ''!''';
CREATE PROCEDURE public.double_value(INOUT value INT, OUT doubled INT)
  SECURITY DEFINER LANGUAGE PLpgSQL AS $$
BEGIN
  doubled := value * 2;
  value := value + 1;
END
$$;
"#;

    let (source_db, target_db, migration) =
        migrate_and_assert_converges(&admin, schema, "", "routine-options-bootstrap").await;
    assert!(migration.contains("SECURITY DEFINER"), "{migration}");
    assert!(migration.contains("DEFAULT 'hello'"), "{migration}");
    assert!(migration.contains("INOUT value INT8"), "{migration}");

    let source_catalog = introspect_url(&source_db.url, &IntrospectOptions::default())
        .await
        .unwrap();
    let json = serde_json::to_string_pretty(&source_catalog).unwrap();
    let round_trip = serde_json::from_str(&json).unwrap();
    assert!(
        diff(&source_catalog, &round_trip).is_empty(),
        "CockroachDB routine catalog JSON must round-trip"
    );

    let mut conn = dpm::introspect::connect(&target_db.url).await.unwrap();
    let greeting: String = sqlx::query_scalar("SELECT public.secure_greeting()")
        .fetch_one(&mut conn)
        .await
        .unwrap();
    let values: (i64, i64) = sqlx::query_as("CALL public.double_value(3, NULL)")
        .fetch_one(&mut conn)
        .await
        .unwrap();
    assert_eq!(greeting, "hello!");
    assert_eq!(values, (4, 6));

    source_db.drop_db().await;
    target_db.drop_db().await;
    assert_converges(&admin, "", schema, "routine-options-teardown").await;
}

#[tokio::test]
async fn cockroach_multiple_conditional_triggers_converge_and_execute() {
    let Some(admin) = admin_url() else { return };
    let source_sql = r#"
CREATE TABLE public.events (id INT PRIMARY KEY, value INT NOT NULL);
CREATE TABLE public.event_audit (event_id INT NOT NULL, observed_value INT NOT NULL);
CREATE FUNCTION public.normalize_event() RETURNS TRIGGER LANGUAGE PLpgSQL AS $$
BEGIN
  IF (NEW).value < 0 THEN
    NEW.value := 0;
  END IF;
  RETURN NEW;
END
$$;
CREATE FUNCTION public.audit_event() RETURNS TRIGGER LANGUAGE PLpgSQL AS $$
BEGIN
  INSERT INTO public.event_audit(event_id, observed_value)
    VALUES ((NEW).id, (NEW).value);
  RETURN NEW;
END
$$;
CREATE TRIGGER events_normalize BEFORE INSERT OR UPDATE ON public.events
  FOR EACH ROW EXECUTE FUNCTION public.normalize_event();
CREATE TRIGGER events_audit_insert AFTER INSERT ON public.events
  FOR EACH ROW WHEN ((NEW).value > 10)
  EXECUTE FUNCTION public.audit_event();
CREATE TRIGGER events_audit_update AFTER UPDATE ON public.events
  FOR EACH ROW WHEN ((NEW).value > 20)
  EXECUTE FUNCTION public.audit_event();
"#;
    let target_sql = r#"
CREATE TABLE public.events (id INT PRIMARY KEY, value INT NOT NULL);
CREATE TABLE public.event_audit (event_id INT NOT NULL, observed_value INT NOT NULL);
CREATE FUNCTION public.normalize_event() RETURNS TRIGGER LANGUAGE PLpgSQL AS $$
BEGIN
  IF (NEW).value < 0 THEN
    NEW.value := 99;
  END IF;
  RETURN NEW;
END
$$;
CREATE FUNCTION public.audit_event() RETURNS TRIGGER LANGUAGE PLpgSQL AS $$
BEGIN
  INSERT INTO public.event_audit(event_id, observed_value)
    VALUES ((NEW).id, -1);
  RETURN NEW;
END
$$;
CREATE TRIGGER events_normalize BEFORE INSERT OR UPDATE ON public.events
  FOR EACH ROW EXECUTE FUNCTION public.normalize_event();
CREATE TRIGGER events_audit_insert AFTER INSERT ON public.events
  FOR EACH ROW WHEN ((NEW).value > 10)
  EXECUTE FUNCTION public.audit_event();
CREATE TRIGGER events_audit_update AFTER UPDATE ON public.events
  FOR EACH ROW WHEN ((NEW).value > 20)
  EXECUTE FUNCTION public.audit_event();
CREATE TRIGGER events_audit_obsolete AFTER INSERT ON public.events
  FOR EACH ROW WHEN ((NEW).value > 1000)
  EXECUTE FUNCTION public.audit_event();
"#;

    let (source_db, target_db, migration) = migrate_and_assert_converges(
        &admin,
        source_sql,
        target_sql,
        "multiple-conditional-triggers",
    )
    .await;
    for name in [
        "events_normalize",
        "events_audit_insert",
        "events_audit_update",
        "events_audit_obsolete",
    ] {
        assert!(
            migration.contains(&format!("DROP TRIGGER IF EXISTS \"{name}\"")),
            "missing trigger dependency drop for {name}:\n{migration}"
        );
    }

    let mut conn = dpm::introspect::connect(&target_db.url).await.unwrap();
    sqlx::raw_sql(
        "INSERT INTO public.events (id, value) VALUES (1, -5), (2, 15), (3, 25); \
         UPDATE public.events SET value = 30 WHERE id = 2; \
         UPDATE public.events SET value = -7 WHERE id = 1;",
    )
    .execute(&mut conn)
    .await
    .expect("execute migrated CockroachDB conditional triggers");
    let values: (i64, i64, i64) = sqlx::query_as(
        "SELECT max(value) FILTER (WHERE id = 1)::INT8, \
                max(value) FILTER (WHERE id = 2)::INT8, \
                max(value) FILTER (WHERE id = 3)::INT8 \
           FROM public.events",
    )
    .fetch_one(&mut conn)
    .await
    .unwrap();
    let audit: (i64, i64) =
        sqlx::query_as("SELECT count(*)::INT8, sum(observed_value)::INT8 FROM public.event_audit")
            .fetch_one(&mut conn)
            .await
            .unwrap();
    assert_eq!(values, (0, 30, 25));
    assert_eq!(audit, (3, 70));

    source_db.drop_db().await;
    target_db.drop_db().await;
}

#[tokio::test]
async fn cockroach_advanced_indexes_converge() {
    let Some(admin) = admin_url() else { return };
    let (source_db, target_db, migration) = migrate_and_assert_converges(
        &admin,
        ADVANCED_INDEX_SOURCE,
        ADVANCED_INDEX_TARGET,
        "advanced-indexes",
    )
    .await;
    assert!(
        migration.contains("DROP INDEX IF EXISTS \"public\".\"documents_obsolete_idx\""),
        "{migration}"
    );
    assert!(
        migration.contains("DROP INDEX IF EXISTS \"public\".\"documents_obsolete_unique_idx\""),
        "{migration}"
    );
    source_db.drop_db().await;
    target_db.drop_db().await;
}

#[tokio::test]
async fn cockroach_rls_policy_converges() {
    let Some(admin) = admin_url() else { return };
    assert_converges(&admin, RLS_SOURCE, RLS_TARGET, "rls-policy").await;
}

#[tokio::test]
async fn cockroach_hostile_identifiers_converge() {
    let Some(admin) = admin_url() else { return };
    assert_converges(
        &admin,
        "CREATE SCHEMA \"odd schema\"; \
         CREATE TABLE \"odd schema\".\"select\" (\"a.b\" INT PRIMARY KEY, \"say\"\"hi\" STRING); \
         CREATE INDEX \"index with spaces\" ON \"odd schema\".\"select\" (\"say\"\"hi\");",
        "",
        "hostile-identifiers",
    )
    .await;
}

#[tokio::test]
async fn cockroach_column_transitions_converge() {
    let Some(admin) = admin_url() else { return };
    assert_converges(
        &admin,
        COLUMN_TRANSITION_SOURCE,
        COLUMN_TRANSITION_TARGET,
        "column-transitions",
    )
    .await;
}

#[tokio::test]
async fn cockroach_populated_table_preserves_data() {
    let Some(admin) = admin_url() else { return };
    let source_db = fresh_db(&admin).await;
    let target_db = fresh_db(&admin).await;
    source_db
        .apply_sql(
            "CREATE TABLE public.readings (\
               id INT PRIMARY KEY, value INT NOT NULL, \
               category STRING NOT NULL DEFAULT 'general', \
               CONSTRAINT readings_value_check CHECK (value >= 0)); \
             CREATE INDEX readings_category_idx ON public.readings (category);",
        )
        .await
        .unwrap();
    target_db
        .apply_sql(
            "CREATE TABLE public.readings (id INT PRIMARY KEY, value INT NOT NULL); \
             INSERT INTO public.readings (id, value) SELECT n, n * 3 FROM generate_series(1, 250) AS g(n);",
        )
        .await
        .unwrap();

    let opts = IntrospectOptions::default();
    let source = introspect_url(&source_db.url, &opts).await.unwrap();
    let target = introspect_url(&target_db.url, &opts).await.unwrap();
    let script = emit(
        &diff(&source, &target),
        &EmitOptions {
            allow_destructive: true,
            database_flavor: DatabaseFlavor::Cockroach,
            ..Default::default()
        },
    );
    assert!(script.sql.contains("NOT VALID"), "{}", script.sql);
    assert!(script.sql.contains("VALIDATE CONSTRAINT"), "{}", script.sql);
    apply_script(&target_db.url, &script.sql)
        .await
        .unwrap_or_else(|error| {
            panic!(
                "populated CockroachDB migration failed: {error:#}\n{}",
                script.sql
            )
        });

    let mut conn = dpm::introspect::connect(&target_db.url).await.unwrap();
    let stats: (i64, i64, i64) = sqlx::query_as(
        "SELECT count(*)::INT8, sum(value)::INT8, \
                count(*) FILTER (WHERE category = 'general')::INT8 \
         FROM public.readings",
    )
    .fetch_one(&mut conn)
    .await
    .unwrap();
    assert_eq!(
        stats,
        (250, 94_125, 250),
        "migration changed existing rows or missed the default backfill"
    );

    let migrated = introspect_url(&target_db.url, &opts).await.unwrap();
    assert!(
        diff(&source, &migrated).is_empty(),
        "populated CockroachDB migration must converge"
    );
    source_db.drop_db().await;
    target_db.drop_db().await;
}

#[tokio::test]
async fn cockroach_implicit_hidden_rowid_survives_bootstrap() {
    let Some(admin) = admin_url() else { return };
    let source_db = fresh_db(&admin).await;
    let target_db = fresh_db(&admin).await;
    source_db
        .apply_sql("CREATE TABLE public.events (payload STRING NOT NULL);")
        .await
        .unwrap();

    let opts = IntrospectOptions::default();
    let source = introspect_url(&source_db.url, &opts).await.unwrap();
    let rowid = source
        .tables
        .values()
        .next()
        .unwrap()
        .column("rowid")
        .expect("CockroachDB should expose its implicit rowid");
    assert!(
        rowid.hidden,
        "implicit CockroachDB rowid must introspect as hidden"
    );

    let script = emit(
        &diff(
            &source,
            &introspect_url(&target_db.url, &opts).await.unwrap(),
        ),
        &EmitOptions {
            allow_destructive: true,
            database_flavor: DatabaseFlavor::Cockroach,
            ..Default::default()
        },
    );
    assert!(script.sql.contains("NOT VISIBLE"), "{}", script.sql);
    apply_script(&target_db.url, &script.sql).await.unwrap();

    let hidden: bool = sqlx::query_scalar(
        "SELECT is_hidden = 'YES' FROM information_schema.columns \
         WHERE table_schema = 'public' AND table_name = 'events' AND column_name = 'rowid'",
    )
    .fetch_one(&mut dpm::introspect::connect(&target_db.url).await.unwrap())
    .await
    .unwrap();
    assert!(hidden, "bootstrapped rowid must remain hidden");
    let migrated = introspect_url(&target_db.url, &opts).await.unwrap();
    assert!(diff(&source, &migrated).is_empty());

    source_db.drop_db().await;
    target_db.drop_db().await;
}

#[tokio::test]
async fn cockroach_column_visibility_change_converges() {
    let Some(admin) = admin_url() else { return };
    assert_converges(
        &admin,
        "CREATE TABLE public.secrets (id INT PRIMARY KEY, token STRING NOT VISIBLE);",
        "CREATE TABLE public.secrets (id INT PRIMARY KEY, token STRING);",
        "column-visibility",
    )
    .await;
}

#[tokio::test]
async fn cockroach_sql_file_materializes_and_bootstraps_via_cli() {
    let Some(admin) = admin_url() else { return };
    let fixture = format!(
        "{}/tests/fixtures/cockroach_schema.sql",
        env!("CARGO_MANIFEST_DIR")
    );
    let opts = IntrospectOptions::default();
    let context = ResolveContext {
        introspect: &opts,
        shadow_url: Some(admin.clone()),
        keep_shadow: false,
        verbose: false,
    };
    let materialized = resolve(&SideSpec::SqlPath(fixture.clone()), &context)
        .await
        .expect("materialize CockroachDB SQL fixture");
    assert_eq!(materialized.database_flavor, DatabaseFlavor::Cockroach);

    let direct = fresh_db(&admin).await;
    direct
        .apply_sql(&std::fs::read_to_string(&fixture).unwrap())
        .await
        .unwrap();
    let direct_catalog = introspect_url(&direct.url, &opts).await.unwrap();
    assert!(
        diff(&materialized, &direct_catalog).is_empty(),
        "SQL materialization must match a directly-created CockroachDB schema"
    );

    let output = Command::new(env!("CARGO_BIN_EXE_dpm"))
        .args(["bootstrap", "--source-sql", &fixture, "--shadow", &admin])
        .output()
        .expect("run CockroachDB SQL-file bootstrap");
    assert!(
        output.status.success(),
        "CockroachDB bootstrap failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("dialect: CockroachDB"), "{stdout}");
    assert!(
        stdout.contains("CREATE TABLE IF NOT EXISTS \"inventory\".\"products\""),
        "{stdout}"
    );

    direct.drop_db().await;
}
