//! Integration tests against a real Postgres server.
//!
//! Gated on DPM_TEST_DATABASE_URL (an admin URL where the role may CREATE
//! DATABASE, e.g. from `scripts/ephemeral-pg.sh start`). When unset, every
//! test is a silent pass so plain `cargo test` works offline.
//!
//! The gold-standard assertion is *convergence*: after applying the generated
//! migration to the target, re-diffing source vs target yields zero changes.

use dpm::apply::apply_script;
use dpm::diff::diff;
use dpm::emit::{emit, EmitOptions};
use dpm::introspect::{introspect_url, IntrospectOptions};
use dpm::source::{replace_database_in_url, ShadowDb};

fn admin_url() -> Option<String> {
    match std::env::var("DPM_TEST_DATABASE_URL") {
        Ok(v) if !v.is_empty() => Some(v),
        _ => {
            eprintln!("skipping: DPM_TEST_DATABASE_URL not set (run scripts/test.sh)");
            None
        }
    }
}

async fn fresh_db(admin: &str) -> ShadowDb {
    ShadowDb::create(admin, false).await.expect("create test database")
}

/// A schema exercising every object class dpm covers: enums, serial +
/// identity + generated columns, defaults, collations are skipped (portable),
/// PK/unique/check/FK constraints, partial + expression indexes, standalone
/// sequences, views, materialized views, functions, triggers, RLS + policies,
/// a second schema, and an extension.
const RICH_SCHEMA: &str = r#"
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA app;

CREATE TYPE public.mood AS ENUM ('sad', 'ok', 'happy');

CREATE SEQUENCE public.ticket_counter AS bigint INCREMENT BY 5 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100 CACHE 1 NO CYCLE;

CREATE TABLE public.users (
  id bigserial NOT NULL,
  email text NOT NULL,
  current_mood public.mood NOT NULL DEFAULT 'ok',
  bio text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_email_key UNIQUE (email),
  CONSTRAINT users_bio_len CHECK (octet_length(bio) <= 10000)
);
CREATE INDEX users_created_idx ON public.users (created_at DESC);
CREATE UNIQUE INDEX users_email_lower_idx ON public.users (lower(email));

CREATE TABLE public.posts (
  id integer GENERATED ALWAYS AS IDENTITY,
  author_id bigint NOT NULL,
  title text NOT NULL,
  title_len integer GENERATED ALWAYS AS (length(title)) STORED,
  published boolean NOT NULL DEFAULT false,
  CONSTRAINT posts_pkey PRIMARY KEY (id),
  CONSTRAINT posts_author_fkey FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE CASCADE
);
CREATE INDEX posts_published_partial_idx ON public.posts (author_id) WHERE published;

CREATE TABLE app.audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  actor bigint,
  action text NOT NULL,
  at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);

ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY posts_owner_select ON public.posts AS PERMISSIVE FOR SELECT USING (published);

CREATE VIEW public.published_posts AS
  SELECT p.id, p.title, u.email AS author_email
  FROM public.posts p JOIN public.users u ON u.id = p.author_id
  WHERE p.published;

CREATE MATERIALIZED VIEW public.mood_counts AS
  SELECT current_mood, count(*) AS n FROM public.users GROUP BY current_mood;

CREATE FUNCTION public.touch_created() RETURNS trigger AS $fn$
BEGIN
  NEW.created_at := now();
  RETURN NEW;
END;
$fn$ LANGUAGE plpgsql;

CREATE TRIGGER users_touch BEFORE INSERT ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.touch_created();
"#;

/// A divergent evolution of the same database: everything above plus/minus —
/// enum value inserted mid-list, columns added/removed/retyped, constraint
/// changed, index changed, view changed, function body changed, trigger
/// dropped, policy changed, new table, dropped table.
const DIVERGENT_SCHEMA: &str = r#"
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA app;

CREATE TYPE public.mood AS ENUM ('sad', 'ok', 'happy');

CREATE TABLE public.users (
  id bigserial NOT NULL,
  email text NOT NULL,
  current_mood public.mood NOT NULL DEFAULT 'sad',
  legacy_flag boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_bio_len CHECK (octet_length(email) <= 5000)
);
CREATE INDEX users_created_idx ON public.users (created_at);

CREATE TABLE public.stale_stats (
  day date NOT NULL,
  hits integer NOT NULL DEFAULT 0,
  CONSTRAINT stale_stats_pkey PRIMARY KEY (day)
);

CREATE VIEW public.published_posts AS
  SELECT u.id, u.email AS author_email FROM public.users u;

CREATE FUNCTION public.touch_created() RETURNS trigger AS $fn$
BEGIN
  NEW.created_at := clock_timestamp();
  RETURN NEW;
END;
$fn$ LANGUAGE plpgsql;
"#;

async fn setup_pair(admin: &str, source_sql: &str, target_sql: &str) -> (ShadowDb, ShadowDb) {
    let source = fresh_db(admin).await;
    let target = fresh_db(admin).await;
    source.apply_sql(source_sql).await.expect("populate source");
    target.apply_sql(target_sql).await.expect("populate target");
    (source, target)
}

fn opts() -> IntrospectOptions {
    IntrospectOptions::default()
}

/// Core invariant: migrate target → re-diff → empty plan.
async fn assert_converges(admin: &str, source_sql: &str, target_sql: &str, label: &str) {
    let (source_db, target_db) = setup_pair(admin, source_sql, target_sql).await;

    let source = introspect_url(&source_db.url, &opts()).await.expect("introspect source");
    let target = introspect_url(&target_db.url, &opts()).await.expect("introspect target");

    let plan = diff(&source, &target);
    let script = emit(&plan, &EmitOptions { allow_destructive: true, ..Default::default() });

    apply_script(&target_db.url, &script.sql)
        .await
        .unwrap_or_else(|e| panic!("[{label}] applying generated migration failed: {e:#}\n--- script ---\n{}", script.sql));

    let migrated = introspect_url(&target_db.url, &opts()).await.expect("re-introspect target");
    let residual = diff(&source, &migrated);
    let residual_script = emit(&residual, &EmitOptions::default());
    assert!(
        residual.is_empty(),
        "[{label}] did not converge; residual changes:\n{}\n--- original script ---\n{}",
        residual_script.sql,
        script.sql
    );

    source_db.drop_db().await;
    target_db.drop_db().await;
}

#[tokio::test]
async fn bootstrap_empty_target_converges() {
    let Some(admin) = admin_url() else { return };
    assert_converges(&admin, RICH_SCHEMA, "", "bootstrap").await;
}

#[tokio::test]
async fn divergent_target_converges() {
    let Some(admin) = admin_url() else { return };
    assert_converges(&admin, RICH_SCHEMA, DIVERGENT_SCHEMA, "divergent").await;
}

#[tokio::test]
async fn teardown_to_empty_converges() {
    let Some(admin) = admin_url() else { return };
    // Everything in the target must be droppable down to an empty database.
    assert_converges(&admin, "", RICH_SCHEMA, "teardown").await;
}

#[tokio::test]
async fn identical_databases_produce_empty_plan() {
    let Some(admin) = admin_url() else { return };
    let (a, b) = setup_pair(&admin, RICH_SCHEMA, RICH_SCHEMA).await;
    let ca = introspect_url(&a.url, &opts()).await.unwrap();
    let cb = introspect_url(&b.url, &opts()).await.unwrap();
    let plan = diff(&ca, &cb);
    let script = emit(&plan, &EmitOptions::default());
    assert!(plan.is_empty(), "identical databases must diff clean:\n{}", script.sql);
    a.drop_db().await;
    b.drop_db().await;
}

#[tokio::test]
async fn enum_value_insertion_positions_correctly() {
    let Some(admin) = admin_url() else { return };
    let source_sql = "CREATE TYPE public.level AS ENUM ('low', 'medium', 'high', 'critical');";
    let target_sql = "CREATE TYPE public.level AS ENUM ('low', 'high');";
    assert_converges(&admin, source_sql, target_sql, "enum-insert").await;
}

#[tokio::test]
async fn catalog_dump_round_trips_through_json() {
    let Some(admin) = admin_url() else { return };
    let db = fresh_db(&admin).await;
    db.apply_sql(RICH_SCHEMA).await.unwrap();
    let cat = introspect_url(&db.url, &opts()).await.unwrap();
    let json = serde_json::to_string_pretty(&cat).unwrap();
    let back: dpm::model::Catalog = serde_json::from_str(&json).unwrap();
    assert!(diff(&cat, &back).is_empty());
    db.drop_db().await;
}

#[tokio::test]
async fn verify_reports_convergence() {
    let Some(admin) = admin_url() else { return };
    let (source_db, target_db) = setup_pair(&admin, RICH_SCHEMA, DIVERGENT_SCHEMA).await;
    let source = introspect_url(&source_db.url, &opts()).await.unwrap();
    let target = introspect_url(&target_db.url, &opts()).await.unwrap();

    let outcome = dpm::verify::verify(dpm::verify::VerifyParams {
        source: &source,
        target: &target,
        shadow_server_url: &admin,
        source_url_for_external: Some(&source_db.url),
        allow_destructive: true,
        external_check: None,
        checks: Default::default(),
        bins: Default::default(),
        keep_shadow: false,
        verbose: false,
        introspect: &opts(),
    })
    .await
    .expect("verify run");
    assert!(outcome.converged, "verify must converge; residual:\n{:?}", outcome.residual_sql);

    source_db.drop_db().await;
    target_db.drop_db().await;
}

#[tokio::test]
async fn url_db_replacement_used_by_shadow_is_sane() {
    // Pure test, runs without a server.
    assert_eq!(
        replace_database_in_url("postgres://u@h:1/x?a=b", "y").unwrap(),
        "postgres://u@h:1/y?a=b"
    );
}

// ---------------------------------------------------------------------------
// Source/target kind combinations: url ↔ sql-file ↔ catalog-json.
// ---------------------------------------------------------------------------

fn scratch_path(name: &str) -> std::path::PathBuf {
    let dir = std::env::temp_dir().join(format!("dpm-combo-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    dir.join(name)
}

async fn resolve_side(spec: &str, admin: &str) -> dpm::model::Catalog {
    let o = opts();
    let ctx = dpm::source::ResolveContext {
        introspect: &o,
        shadow_url: Some(admin.to_string()),
        keep_shadow: false,
        verbose: false,
    };
    dpm::source::resolve(&dpm::source::SideSpec::parse(spec).unwrap(), &ctx)
        .await
        .unwrap_or_else(|e| panic!("resolving {spec}: {e:#}"))
}

/// Every pairing of (url, .sql, .json) on both sides must produce the same
/// plan for the same underlying schemas.
#[tokio::test]
async fn all_side_kind_combinations_agree() {
    let Some(admin) = admin_url() else { return };

    // Materialize RICH as a live db + catalog.json; DIVERGENT likewise.
    let (source_db, target_db) = setup_pair(&admin, RICH_SCHEMA, DIVERGENT_SCHEMA).await;
    let source_json = scratch_path("source.json");
    let target_json = scratch_path("target.json");
    let source_sql = scratch_path("source.sql");
    let target_sql = scratch_path("target.sql");
    std::fs::write(&source_sql, RICH_SCHEMA).unwrap();
    std::fs::write(&target_sql, DIVERGENT_SCHEMA).unwrap();
    let source_cat = introspect_url(&source_db.url, &opts()).await.unwrap();
    let target_cat = introspect_url(&target_db.url, &opts()).await.unwrap();
    std::fs::write(&source_json, serde_json::to_string(&source_cat).unwrap()).unwrap();
    std::fs::write(&target_json, serde_json::to_string(&target_cat).unwrap()).unwrap();

    let source_kinds = [source_db.url.clone(), source_sql.display().to_string(), source_json.display().to_string()];
    let target_kinds = [target_db.url.clone(), target_sql.display().to_string(), target_json.display().to_string()];

    // Reference plan from url ↔ url.
    let reference = emit(&diff(&source_cat, &target_cat), &EmitOptions { allow_destructive: true, ..Default::default() });

    for s in &source_kinds {
        for t in &target_kinds {
            let sc = resolve_side(s, &admin).await;
            let tc = resolve_side(t, &admin).await;
            let script = emit(&diff(&sc, &tc), &EmitOptions { allow_destructive: true, ..Default::default() });
            assert_eq!(
                script.sql, reference.sql,
                "combo source={s} target={t} produced a different migration"
            );
        }
    }

    source_db.drop_db().await;
    target_db.drop_db().await;
}

/// A pg_dump --schema-only style dump (SET headers, psql \\restrict
/// meta-commands, OWNER TO / GRANT statements for roles that don't exist on
/// the shadow server) must materialize and diff clean against the live
/// database it was dumped from.
#[tokio::test]
async fn pg_dump_style_sql_file_materializes() {
    let Some(admin) = admin_url() else { return };
    let live = fresh_db(&admin).await;
    live.apply_sql("CREATE TABLE things (id bigserial PRIMARY KEY, name text NOT NULL);")
        .await
        .unwrap();

    let dump = r#"--
-- PostgreSQL database dump
--

\restrict h4xEcgNiOtVIatCVdEmDJRuqCXhZUAdOTgeCFyi0ZZuBcpNZZBLzB0oFAlwuvtA

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SELECT pg_catalog.set_config('search_path', '', false);
SET row_security = off;

CREATE TABLE public.things (
    id bigint NOT NULL,
    name text NOT NULL
);

ALTER TABLE public.things OWNER TO production_role_that_does_not_exist;

CREATE SEQUENCE public.things_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.things_id_seq OWNER TO production_role_that_does_not_exist;
ALTER SEQUENCE public.things_id_seq OWNED BY public.things.id;
ALTER TABLE ONLY public.things ALTER COLUMN id SET DEFAULT nextval('public.things_id_seq'::regclass);
ALTER TABLE ONLY public.things ADD CONSTRAINT things_pkey PRIMARY KEY (id);

GRANT ALL ON TABLE public.things TO some_app_role;

\unrestrict h4xEcgNiOtVIatCVdEmDJRuqCXhZUAdOTgeCFyi0ZZuBcpNZZBLzB0oFAlwuvtA

--
-- PostgreSQL database dump complete
--
"#;
    let dump_path = scratch_path("pg-dump-style.sql");
    std::fs::write(&dump_path, dump).unwrap();

    let from_dump = resolve_side(&dump_path.display().to_string(), &admin).await;
    let from_live = introspect_url(&live.url, &opts()).await.unwrap();
    let plan = diff(&from_dump, &from_live);
    let script = emit(&plan, &EmitOptions::default());
    assert!(
        plan.is_empty(),
        "dump-materialized catalog must match the live db it was dumped from:\n{}",
        script.sql
    );
    live.drop_db().await;
}

/// The destructive two-consent model: --allow-destructive-sql controls
/// generation; without --allow-destructive-ops the CLI apply path must refuse
/// to execute live destructive SQL (exercised at the library level here via
/// the same counts the CLI uses).
#[tokio::test]
async fn destructive_counts_drive_the_two_consent_gate() {
    let Some(admin) = admin_url() else { return };
    let (source_db, target_db) = setup_pair(&admin, "", "CREATE TABLE doomed (id int);").await;
    let source = introspect_url(&source_db.url, &opts()).await.unwrap();
    let target = introspect_url(&target_db.url, &opts()).await.unwrap();
    let plan = diff(&source, &target);

    // sql-consent off: everything destructive is gated; nothing live to run.
    let gated = emit(&plan, &EmitOptions::default());
    assert_eq!(gated.destructive_count, 1);
    assert_eq!(gated.gated_count, 1);
    assert_eq!(gated.destructive_count - gated.gated_count, 0);

    // sql-consent on: one live destructive statement — the ops gate (in the
    // CLI) must see live_destructive = 1.
    let live = emit(&plan, &EmitOptions { allow_destructive: true, ..Default::default() });
    assert_eq!(live.destructive_count - live.gated_count, 1);

    source_db.drop_db().await;
    target_db.drop_db().await;
}

// ===========================================================================
// Cross-checker matrix: every fixture pair is verified by dpm AND by every
// installed external tool (migra, pgdiff, atlas, pg-schema-diff, liquibase,
// apgdiff, flyway). Missing tools are skipped by --cross-check-all
// semantics, so the matrix degrades gracefully on machines without them.
// ===========================================================================

async fn verify_with_all_checkers(admin: &str, label: &str, source_sql: &str, target_sql: &str) {
    let (source_db, target_db) = setup_pair(admin, source_sql, target_sql).await;
    let source = introspect_url(&source_db.url, &opts()).await.unwrap();
    let target = introspect_url(&target_db.url, &opts()).await.unwrap();

    let outcome = dpm::verify::verify(dpm::verify::VerifyParams {
        source: &source,
        target: &target,
        shadow_server_url: admin,
        source_url_for_external: Some(&source_db.url),
        allow_destructive: true,
        external_check: None,
        checks: dpm::crosscheck::CheckSelection { all: true, ..Default::default() },
        bins: Default::default(),
        keep_shadow: false,
        verbose: false,
        introspect: &opts(),
    })
    .await
    .unwrap_or_else(|e| panic!("[{label}] verify failed: {e:#}"));

    assert!(
        outcome.converged,
        "[{label}] dpm did not converge:\n{}",
        outcome.residual_sql.as_deref().unwrap_or("")
    );
    let ran: Vec<&str> = outcome.checks.iter().map(|c| c.name.as_str()).collect();
    eprintln!("[{label}] cross-checkers ran: {ran:?}");
    for check in &outcome.checks {
        assert!(
            check.agreed,
            "[{label}] {} disagreed with dpm:\nerror: {:?}\noutput:\n{}\ncommand: {}",
            check.name, check.error, check.output, check.command
        );
    }

    source_db.drop_db().await;
    target_db.drop_db().await;
}

#[tokio::test]
async fn matrix_divergent_all_checkers() {
    let Some(admin) = admin_url() else { return };
    verify_with_all_checkers(&admin, "divergent", RICH_SCHEMA, DIVERGENT_SCHEMA).await;
}

#[tokio::test]
async fn matrix_bootstrap_all_checkers() {
    let Some(admin) = admin_url() else { return };
    verify_with_all_checkers(&admin, "bootstrap", RICH_SCHEMA, "").await;
}

#[tokio::test]
async fn matrix_teardown_all_checkers() {
    let Some(admin) = admin_url() else { return };
    verify_with_all_checkers(&admin, "teardown", "", RICH_SCHEMA).await;
}

#[tokio::test]
async fn matrix_enum_evolution() {
    let Some(admin) = admin_url() else { return };
    verify_with_all_checkers(
        &admin,
        "enum",
        "CREATE TYPE level AS ENUM ('low','medium','high','critical');\n\
         CREATE TABLE alerts (id bigserial PRIMARY KEY, sev level NOT NULL DEFAULT 'low');",
        "CREATE TYPE level AS ENUM ('low','high');\n\
         CREATE TABLE alerts (id bigserial PRIMARY KEY, sev level NOT NULL DEFAULT 'high');",
    )
    .await;
}

#[tokio::test]
async fn matrix_serial_identity_transitions() {
    let Some(admin) = admin_url() else { return };
    verify_with_all_checkers(
        &admin,
        "serial-identity",
        "CREATE TABLE a (id bigserial PRIMARY KEY, n integer NOT NULL DEFAULT 0);\n\
         CREATE TABLE b (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY);\n\
         CREATE TABLE c (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);",
        "CREATE TABLE a (id bigserial PRIMARY KEY);\n\
         CREATE TABLE b (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);\n\
         CREATE TABLE c (id integer PRIMARY KEY);",
    )
    .await;
}

#[tokio::test]
async fn matrix_constraint_churn() {
    let Some(admin) = admin_url() else { return };
    verify_with_all_checkers(
        &admin,
        "constraints",
        "CREATE TABLE parent (id bigint PRIMARY KEY, code text NOT NULL, CONSTRAINT parent_code_key UNIQUE (code));\n\
         CREATE TABLE child (id bigserial PRIMARY KEY, parent_id bigint NOT NULL,\n\
           CONSTRAINT child_parent_fkey FOREIGN KEY (parent_id) REFERENCES parent(id) ON DELETE RESTRICT,\n\
           CONSTRAINT child_pos CHECK (id > 0));",
        "CREATE TABLE parent (id bigint PRIMARY KEY, code text NOT NULL);\n\
         CREATE TABLE child (id bigserial PRIMARY KEY, parent_id bigint NOT NULL,\n\
           CONSTRAINT child_parent_fkey FOREIGN KEY (parent_id) REFERENCES parent(id) ON DELETE CASCADE,\n\
           CONSTRAINT child_neg CHECK (id <> 0));",
    )
    .await;
}

#[tokio::test]
async fn matrix_index_churn() {
    let Some(admin) = admin_url() else { return };
    verify_with_all_checkers(
        &admin,
        "indexes",
        "CREATE TABLE t (id bigserial PRIMARY KEY, email text NOT NULL, org bigint NOT NULL, live boolean NOT NULL DEFAULT true);\n\
         CREATE UNIQUE INDEX t_email_lower ON t (lower(email));\n\
         CREATE INDEX t_org_live ON t (org) WHERE live;\n\
         CREATE INDEX t_org_desc ON t (org DESC NULLS LAST);",
        "CREATE TABLE t (id bigserial PRIMARY KEY, email text NOT NULL, org bigint NOT NULL, live boolean NOT NULL DEFAULT true);\n\
         CREATE INDEX t_email_lower ON t (lower(email));\n\
         CREATE INDEX t_org_live ON t (org) WHERE NOT live;",
    )
    .await;
}

#[tokio::test]
async fn matrix_views_functions_triggers() {
    let Some(admin) = admin_url() else { return };
    verify_with_all_checkers(
        &admin,
        "views-fns-triggers",
        "CREATE TABLE ev (id bigserial PRIMARY KEY, kind text NOT NULL, at timestamptz NOT NULL DEFAULT now());\n\
         CREATE VIEW recent AS SELECT id, kind FROM ev WHERE at > now() - interval '1 day';\n\
         CREATE MATERIALIZED VIEW kinds AS SELECT kind, count(*) n FROM ev GROUP BY kind;\n\
         CREATE FUNCTION bump() RETURNS trigger AS $f$ BEGIN NEW.at := now(); RETURN NEW; END; $f$ LANGUAGE plpgsql;\n\
         CREATE TRIGGER ev_bump BEFORE UPDATE ON ev FOR EACH ROW EXECUTE FUNCTION bump();",
        "CREATE TABLE ev (id bigserial PRIMARY KEY, kind text NOT NULL, at timestamptz NOT NULL DEFAULT now());\n\
         CREATE VIEW recent AS SELECT id FROM ev;\n\
         CREATE FUNCTION bump() RETURNS trigger AS $f$ BEGIN NEW.at := clock_timestamp(); RETURN NEW; END; $f$ LANGUAGE plpgsql;",
    )
    .await;
}

#[tokio::test]
async fn matrix_rls_policies() {
    let Some(admin) = admin_url() else { return };
    verify_with_all_checkers(
        &admin,
        "rls",
        "CREATE TABLE docs (id bigserial PRIMARY KEY, owner text NOT NULL, open boolean NOT NULL DEFAULT false);\n\
         ALTER TABLE docs ENABLE ROW LEVEL SECURITY;\n\
         CREATE POLICY docs_read ON docs AS PERMISSIVE FOR SELECT USING (open);\n\
         CREATE POLICY docs_write ON docs AS RESTRICTIVE FOR UPDATE USING (open) WITH CHECK (open);",
        "CREATE TABLE docs (id bigserial PRIMARY KEY, owner text NOT NULL, open boolean NOT NULL DEFAULT false);\n\
         CREATE POLICY docs_read ON docs AS PERMISSIVE FOR SELECT USING (NOT open);",
    )
    .await;
}

#[tokio::test]
async fn matrix_multischema() {
    let Some(admin) = admin_url() else { return };
    verify_with_all_checkers(
        &admin,
        "multischema",
        "CREATE SCHEMA billing; CREATE SCHEMA audit;\n\
         CREATE TABLE billing.invoices (id bigserial PRIMARY KEY, total numeric(12,2) NOT NULL DEFAULT 0);\n\
         CREATE TABLE audit.entries (id bigserial PRIMARY KEY, ref bigint NOT NULL,\n\
           CONSTRAINT entries_ref_fkey FOREIGN KEY (ref) REFERENCES billing.invoices(id));",
        "CREATE SCHEMA billing;\n\
         CREATE TABLE billing.invoices (id bigserial PRIMARY KEY, total numeric(10,2) NOT NULL);",
    )
    .await;
}

#[tokio::test]
async fn matrix_exclusion_and_extension_churn() {
    let Some(admin) = admin_url() else { return };
    verify_with_all_checkers(
        &admin,
        "exclusion-extension",
        "CREATE EXTENSION IF NOT EXISTS btree_gist;\n\
         CREATE TABLE bookings (id bigserial PRIMARY KEY, room integer NOT NULL, during tsrange NOT NULL,\n\
           CONSTRAINT bookings_no_overlap EXCLUDE USING gist (room WITH =, during WITH &&));",
        "CREATE TABLE bookings (id bigserial PRIMARY KEY, room integer NOT NULL, during tsrange NOT NULL);",
    )
    .await;
}

#[tokio::test]
async fn matrix_sequence_churn() {
    let Some(admin) = admin_url() else { return };
    verify_with_all_checkers(
        &admin,
        "sequences",
        "CREATE SEQUENCE order_numbers AS bigint INCREMENT BY 10 MINVALUE 100 MAXVALUE 999999999 START WITH 100 CACHE 5 CYCLE;\n\
         CREATE SEQUENCE ticket_ids AS integer INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;",
        "CREATE SEQUENCE order_numbers AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 NO CYCLE;\n\
         CREATE SEQUENCE stale_seq AS integer;",
    )
    .await;
}
