//! Render a [`Plan`] as an ordered, reviewable SQL script.
//!
//! Ordering is dependency-driven, in fixed phases:
//!
//!  0. `ALTER TYPE ... ADD VALUE` — outside the transaction (new enum values
//!     cannot be used inside the transaction that adds them, PG 12–17).
//!  1. BEGIN
//!  2. schemas, extensions, new enum types
//!  3. drops of dependents: triggers, policies, views (changed/removed)
//!  4. drops of constraints (FKs first) and indexes (changed/removed)
//!  5. sequences (create/alter)
//!  6. table creates; column-level changes on existing tables
//!  7. destructive drops: columns, tables (gated)
//!  8. re-adds: PK/unique/check/exclusion constraints, indexes, then FKs last
//!  9. views (plain, then materialized)
//! 10. functions, then triggers
//! 11. RLS toggles, policies
//! 12. destructive drops of standalone objects: functions, sequences, enums,
//!     extensions (gated)
//! 13. COMMIT + summary footer
//!
//! House rules carried over from prior art (`pg-defs` diff tooling):
//! reviewable SQL only, destructive statements are commented out unless
//! explicitly allowed, constraint adds on existing tables use
//! `NOT VALID` + `VALIDATE`, and every generated file ends with a change
//! count footer.

use std::fmt::Write as _;

use crate::diff::{Change, Plan};
use crate::model::*;

#[derive(Clone, Debug, Default)]
pub struct EmitOptions {
    /// Render destructive statements live instead of commented out.
    pub allow_destructive: bool,
    /// SQL dialect selected from the desired catalog.  The current first-class
    /// CockroachDB surface is intentionally restricted to objects its
    /// compatibility catalog can deparse reliably.
    pub database_flavor: DatabaseFlavor,
    /// Optional provenance lines for the header (source/target descriptions).
    pub source_desc: Option<String>,
    pub target_desc: Option<String>,
}

#[derive(Debug)]
pub struct Script {
    pub sql: String,
    pub change_count: usize,
    pub destructive_count: usize,
    /// Destructive statements that were rendered as comments (i.e. gated).
    pub gated_count: usize,
    pub manual_count: usize,
}

struct Emitter {
    out: String,
    change_count: usize,
    destructive_count: usize,
    gated_count: usize,
    manual_count: usize,
    allow_destructive: bool,
    database_flavor: DatabaseFlavor,
}

impl Emitter {
    fn line(&mut self, s: &str) {
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) {
        self.out.push('\n');
    }

    fn comment(&mut self, s: &str) {
        for l in s.lines() {
            let _ = writeln!(self.out, "-- {l}");
        }
    }

    /// Emit one logical change consisting of `stmts`; when the change is
    /// destructive and destructive changes are not allowed, the statements
    /// are rendered commented out with a warning.
    fn change(&mut self, note: &str, stmts: &[String], destructive: bool) {
        self.change_count += 1;
        if destructive {
            self.destructive_count += 1;
        }
        if !note.is_empty() {
            self.comment(note);
        }
        if destructive && !self.allow_destructive {
            self.gated_count += 1;
            self.comment("[destructive — gated; re-run with --allow-destructive-sql to generate live]");
            for s in stmts {
                for l in s.lines() {
                    let _ = writeln!(self.out, "-- {l}");
                }
            }
        } else {
            for s in stmts {
                self.line(s);
            }
        }
        self.blank();
    }

    fn manual(&mut self, note: &str) {
        self.change_count += 1;
        self.manual_count += 1;
        self.comment(note);
        self.blank();
    }
}

pub fn emit(plan: &Plan, opts: &EmitOptions) -> Script {
    let mut e = Emitter {
        out: String::new(),
        change_count: 0,
        destructive_count: 0,
        gated_count: 0,
        manual_count: 0,
        allow_destructive: opts.allow_destructive,
        database_flavor: opts.database_flavor,
    };

    e.comment("Generated by declarative-postgres-migrate (dpm)");
    e.comment(&format!("dialect: {}", opts.database_flavor.label()));
    if let Some(s) = &opts.source_desc {
        e.comment(&format!("desired (source): {s}"));
    }
    if let Some(t) = &opts.target_desc {
        e.comment(&format!("current (target): {t}"));
    }
    e.comment("Converges the target onto the source. Review before applying.");
    e.comment("dpm never applies SQL unless explicitly told to (dpm apply --yes).");
    e.blank();

    if plan.is_empty() {
        e.comment("No schema differences detected.");
        return finish(e);
    }

    // Phase 0: enum value additions, outside the transaction.
    let adds: Vec<&Change> = plan.changes.iter().filter(|c| matches!(c, Change::AddEnumValue { .. })).collect();
    if !adds.is_empty() {
        e.comment("Enum additions run outside the transaction: a value added inside a");
        e.comment("transaction cannot be referenced until that transaction commits.");
        for c in adds {
            if let Change::AddEnumValue { ty, value, before } = c {
                let pos = match before {
                    Some(b) => format!(" BEFORE {}", quote_literal(b)),
                    None => String::new(),
                };
                e.change(
                    &format!("add enum value: {} += {value}", ty.label()),
                    &[format!(
                        "ALTER TYPE {} ADD VALUE IF NOT EXISTS {}{pos};",
                        ty.sql(),
                        quote_literal(value)
                    )],
                    false,
                );
            }
        }
    }

    e.line("BEGIN;");
    e.blank();

    // Phase 2: schemas, extensions, enum types.
    for c in &plan.changes {
        match c {
            Change::CreateSchema { name } => e.change(
                &format!("create schema: {name}"),
                &[format!("CREATE SCHEMA IF NOT EXISTS {};", quote_ident(name))],
                false,
            ),
            Change::CreateExtension { name } => e.change(
                &format!("create extension: {name}"),
                &[format!("CREATE EXTENSION IF NOT EXISTS {};", quote_ident(name))],
                false,
            ),
            Change::CreateEnum { ty, labels } => {
                let labels_sql = labels.iter().map(|l| quote_literal(l)).collect::<Vec<_>>().join(", ");
                e.change(
                    &format!("create enum: {}", ty.label()),
                    &[format!("CREATE TYPE {} AS ENUM ({labels_sql});", ty.sql())],
                    false,
                );
            }
            Change::EnumNeedsRebuild { ty, source_labels, target_labels } => {
                e.manual(&format!(
                    "MANUAL REVIEW: enum {} labels were removed or reordered.\n\
                     desired: {source_labels:?}\n\
                     current: {target_labels:?}\n\
                     Converging requires a type rebuild (new type, column rewrites, drop old);\n\
                     dpm does not automate enum label removal.",
                    ty.label()
                ));
            }
            _ => {}
        }
    }

    // Phase 3: drops of dependents.
    for c in &plan.changes {
        if let Change::DropTrigger { table, name, replaced } = c {
            e.change(
                &format!("drop trigger: {}.{name}{}", table.label(), replace_tag(*replaced)),
                &[format!("DROP TRIGGER IF EXISTS {} ON {};", quote_ident(name), table.sql())],
                c.is_destructive(),
            );
        }
    }
    for c in &plan.changes {
        if let Change::DropFunction {
            key,
            schema,
            signature,
            kind,
            replaced: true,
        } = c
        {
            e.change(
                &format!("drop {}: {key} (will be recreated below)", kind.label()),
                &[routine_drop_sql(*kind, schema, signature)],
                false,
            );
        }
    }
    for c in &plan.changes {
        if let Change::DropPolicy { table, name, replaced } = c {
            e.change(
                &format!("drop policy: {name} on {}{}", table.label(), replace_tag(*replaced)),
                &[format!("DROP POLICY IF EXISTS {} ON {};", quote_ident(name), table.sql())],
                c.is_destructive(),
            );
        }
    }
    for c in &plan.changes {
        if let Change::DropView { view, materialized, replaced } = c {
            let kw = if *materialized { "MATERIALIZED VIEW" } else { "VIEW" };
            e.change(
                &format!("drop {}: {}{}", kw.to_lowercase(), view.label(), replace_tag(*replaced)),
                &[format!("DROP {kw} IF EXISTS {};", view.sql())],
                c.is_destructive(),
            );
        }
    }

    // Phase 4: constraint drops (FKs first), then index drops.
    let mut ordered_con_drops: Vec<&Change> = plan
        .changes
        .iter()
        .filter(|c| matches!(c, Change::DropConstraint { .. }))
        .collect();
    ordered_con_drops.sort_by_key(|c| match c {
        Change::DropConstraint { kind: ConstraintKind::ForeignKey, .. } => 0,
        _ => 1,
    });
    for c in ordered_con_drops {
        if let Change::DropConstraint {
            table,
            name,
            kind,
            replaced,
        } = c
        {
            // CockroachDB exposes CREATE UNIQUE INDEX entries through
            // pg_constraint, but rejects PostgreSQL's ALTER TABLE ... DROP
            // CONSTRAINT for them. Its supported removal path is DROP INDEX.
            let drop_sql = if e.database_flavor == DatabaseFlavor::Cockroach
                && *kind == ConstraintKind::Unique
            {
                format!(
                    "DROP INDEX IF EXISTS {}.{} CASCADE;",
                    quote_ident(&table.schema),
                    quote_ident(name)
                )
            } else {
                format!(
                    "ALTER TABLE {} DROP CONSTRAINT IF EXISTS {};",
                    table.sql(),
                    quote_ident(name)
                )
            };
            e.change(
                &format!("drop constraint: {name} on {}{}", table.label(), replace_tag(*replaced)),
                &[drop_sql],
                c.is_destructive(),
            );
        }
    }
    for c in &plan.changes {
        if let Change::DropIndex { index, replaced, .. } = c {
            e.change(
                &format!("drop index: {}{}", index.label(), replace_tag(*replaced)),
                &[format!("DROP INDEX IF EXISTS {};", index.sql())],
                c.is_destructive(),
            );
        }
    }

    // Phase 5: sequences.
    for c in &plan.changes {
        match c {
            Change::CreateSequence { seq, def } => {
                e.change(&format!("create sequence: {}", seq.label()), &[sequence_create_sql(seq, def)], false)
            }
            Change::AlterSequence { seq, def } => e.change(
                &format!(
                    "alter sequence: {}\n\
                     The counter is clamped into the new bounds first — Postgres rejects\n\
                     bound changes that strand the current value outside them.",
                    seq.label()
                ),
                &sequence_alter_sql(seq, def),
                false,
            ),
            _ => {}
        }
    }

    // Phase 6: table creates, then per-table column changes.
    for c in &plan.changes {
        if let Change::CreateTable { table, def } = c {
            let statements = create_table_sql(table, def, e.database_flavor);
            e.change(&format!("create table: {}", table.label()), &statements, false);
        }
    }
    for c in &plan.changes {
        match c {
            Change::AddColumn { table, def } => {
                let def_sql = column_def_sql_for_flavor(def, e.database_flavor);
                e.change(
                    &format!("add column: {}.{}", table.label(), def.name),
                    &[format!("ALTER TABLE {} ADD COLUMN IF NOT EXISTS {def_sql};", table.sql())],
                    false,
                );
            }
            Change::AlterColumnType { table, column, from, to, collation } => {
                let collate = collation.as_ref().map(|c| format!(" COLLATE {c}")).unwrap_or_default();
                e.change(
                    &format!(
                        "alter column type: {}.{column}  {from} -> {to}\n\
                         NOTE: may rewrite the table and/or fail on incompatible data; review the USING cast."
                    , table.label()),
                    &[format!(
                        "ALTER TABLE {} ALTER COLUMN {} TYPE {to}{collate} USING {}::{to};",
                        table.sql(),
                        quote_ident(column),
                        quote_ident(column)
                    )],
                    false,
                );
            }
            Change::SetNotNull { table, column } => e.change(
                &format!(
                    "set not null: {}.{column}\n\
                     NOTE: fails if existing rows contain NULLs — backfill first if needed.",
                    table.label()
                ),
                &[format!("ALTER TABLE {} ALTER COLUMN {} SET NOT NULL;", table.sql(), quote_ident(column))],
                false,
            ),
            Change::DropNotNull { table, column } => e.change(
                &format!("drop not null: {}.{column}", table.label()),
                &[format!("ALTER TABLE {} ALTER COLUMN {} DROP NOT NULL;", table.sql(), quote_ident(column))],
                false,
            ),
            Change::SetColumnVisibility { table, column, hidden } => e.change(
                &format!(
                    "set column visibility: {}.{column} -> {}",
                    table.label(),
                    if *hidden { "not visible" } else { "visible" }
                ),
                &[format!(
                    "ALTER TABLE {} ALTER COLUMN {} SET {};",
                    table.sql(),
                    quote_ident(column),
                    if *hidden { "NOT VISIBLE" } else { "VISIBLE" }
                )],
                false,
            ),
            Change::SetDefault { table, column, expr } => e.change(
                &format!("set default: {}.{column}", table.label()),
                &[format!("ALTER TABLE {} ALTER COLUMN {} SET DEFAULT {expr};", table.sql(), quote_ident(column))],
                false,
            ),
            Change::DropDefault { table, column } => e.change(
                &format!("drop default: {}.{column}", table.label()),
                &[format!("ALTER TABLE {} ALTER COLUMN {} DROP DEFAULT;", table.sql(), quote_ident(column))],
                false,
            ),
            Change::MakeSerial { table, column, type_sql } => {
                let seq = serial_sequence_qname(table, column);
                e.change(
                    &format!("make serial: {}.{column} ({type_sql})", table.label()),
                    &[
                        format!("CREATE SEQUENCE IF NOT EXISTS {};", seq.sql()),
                        format!(
                            "ALTER TABLE {} ALTER COLUMN {} SET DEFAULT nextval('{}'::regclass);",
                            table.sql(),
                            quote_ident(column),
                            seq.sql().replace('\'', "''")
                        ),
                        format!("ALTER SEQUENCE {} OWNED BY {}.{};", seq.sql(), table.sql(), quote_ident(column)),
                        format!(
                            "SELECT setval('{}'::regclass, coalesce((SELECT max({}) FROM {}), 0) + 1, false);",
                            seq.sql().replace('\'', "''"),
                            quote_ident(column),
                            table.sql()
                        ),
                    ],
                    false,
                );
            }
            Change::DropSerial { table, column } => {
                let seq = serial_sequence_qname(table, column);
                e.change(
                    &format!(
                        "drop serial default: {}.{column}\n\
                         The owned sequence is dropped with it (its counter is lost).",
                        table.label()
                    ),
                    &[
                        format!("ALTER TABLE {} ALTER COLUMN {} DROP DEFAULT;", table.sql(), quote_ident(column)),
                        format!("DROP SEQUENCE IF EXISTS {};", seq.sql()),
                    ],
                    true,
                );
            }
            Change::AddIdentity { table, column, kind } => e.change(
                &format!("add identity: {}.{column}", table.label()),
                &[format!(
                    "ALTER TABLE {} ALTER COLUMN {} ADD {};",
                    table.sql(),
                    quote_ident(column),
                    kind.sql()
                )],
                false,
            ),
            Change::DropIdentity { table, column } => e.change(
                &format!("drop identity: {}.{column}", table.label()),
                &[format!(
                    "ALTER TABLE {} ALTER COLUMN {} DROP IDENTITY IF EXISTS;",
                    table.sql(),
                    quote_ident(column)
                )],
                false,
            ),
            Change::SetIdentityKind { table, column, kind } => {
                let set = match kind {
                    IdentityKind::Always => "SET GENERATED ALWAYS",
                    IdentityKind::ByDefault => "SET GENERATED BY DEFAULT",
                };
                e.change(
                    &format!("set identity kind: {}.{column}", table.label()),
                    &[format!("ALTER TABLE {} ALTER COLUMN {} {set};", table.sql(), quote_ident(column))],
                    false,
                );
            }
            Change::RegenerateColumn { table, def } => {
                let def_sql = column_def_sql_for_flavor(def, e.database_flavor);
                e.change(
                    &format!(
                        "rebuild generated column: {}.{}\n\
                         Generation expressions cannot be altered in place; the column is\n\
                         dropped and re-added (its stored values are recomputed).",
                        table.label(),
                        def.name
                    ),
                    &[
                        format!("ALTER TABLE {} DROP COLUMN IF EXISTS {};", table.sql(), quote_ident(&def.name)),
                        format!("ALTER TABLE {} ADD COLUMN {def_sql};", table.sql()),
                    ],
                    true,
                );
            }
            _ => {}
        }
    }

    // Phase 7: destructive drops of columns and tables.
    for c in &plan.changes {
        if let Change::DropColumn { table, column } = c {
            e.change(
                &format!("drop column: {}.{column}", table.label()),
                &[format!("ALTER TABLE {} DROP COLUMN IF EXISTS {};", table.sql(), quote_ident(column))],
                true,
            );
        }
    }
    for c in &plan.changes {
        if let Change::DropTable { table } = c {
            e.change(
                &format!("drop table: {}", table.label()),
                &[format!("DROP TABLE IF EXISTS {};", table.sql())],
                true,
            );
        }
    }

    // Phase 8: constraint adds (non-FK first, FKs last), then indexes.
    // FKs belonging to newly created tables are synthesized here (they are
    // not part of the CREATE TABLE statement) so every referenced table
    // already exists regardless of creation order.
    let mut fk_changes: Vec<Change> = Vec::new();
    for c in &plan.changes {
        if let Change::CreateTable { table, def } = c {
            for con in def.constraints.values() {
                if con.kind == ConstraintKind::ForeignKey {
                    fk_changes.push(Change::AddConstraint {
                        table: table.clone(),
                        name: con.name.clone(),
                        def: con.def.clone(),
                        kind: ConstraintKind::ForeignKey,
                        table_is_new: true,
                    });
                }
            }
        }
    }
    let (non_fk, fks): (Vec<&Change>, Vec<&Change>) = plan
        .changes
        .iter()
        .filter(|c| matches!(c, Change::AddConstraint { .. }))
        .partition(|c| !matches!(c, Change::AddConstraint { kind: ConstraintKind::ForeignKey, .. }));
    for c in non_fk {
        emit_add_constraint(&mut e, c);
    }
    for c in &plan.changes {
        if let Change::CreateIndex { table, name, def } = c {
            e.change(
                &format!("create index: {name} on {}", table.label()),
                &[ensure_semicolon(def)],
                false,
            );
        }
    }
    for c in fks {
        emit_add_constraint(&mut e, c);
    }
    for c in &fk_changes {
        emit_add_constraint(&mut e, c);
    }

    // Phase 9: views (plain first — matviews may select from them).
    let mut views: Vec<&Change> = plan.changes.iter().filter(|c| matches!(c, Change::CreateView { .. })).collect();
    views.sort_by_key(|c| matches!(c, Change::CreateView { materialized: true, .. }));
    for c in views {
        if let Change::CreateView { view, materialized, def } = c {
            let stmt = if *materialized {
                format!("CREATE MATERIALIZED VIEW {} AS\n{}", view.sql(), def.trim_end())
            } else {
                format!("CREATE VIEW {} AS\n{}", view.sql(), def.trim_end())
            };
            e.change(
                &format!("create {}: {}", if *materialized { "materialized view" } else { "view" }, view.label()),
                &[ensure_semicolon(&stmt)],
                false,
            );
        }
    }

    // Phase 10: functions/procedures, then triggers.
    for c in &plan.changes {
        if let Change::CreateFunction { key, kind, def, replacing } = c {
            let tag = if *replacing { " (replacing)" } else { "" };
            e.change(
                &format!("create {}: {key}{tag}", kind.label()),
                &[routine_create_sql(def, *replacing)],
                false,
            );
        }
    }
    for c in &plan.changes {
        if let Change::CreateTrigger { key, def, .. } = c {
            e.change(&format!("create trigger: {key}"), &[ensure_semicolon(def)], false);
        }
    }
    for c in &plan.changes {
        if let Change::SetTriggerMode { table, name, mode } = c {
            e.change(
                &format!("set trigger mode: {}.{name}", table.label()),
                &[format!(
                    "ALTER TABLE {} {} {};",
                    table.sql(),
                    mode.alter_sql(),
                    quote_ident(name)
                )],
                false,
            );
        }
    }

    // Phase 11: RLS + policies. Newly created tables carry their RLS state
    // and policies inside the CreateTable def; synthesize those here.
    for c in &plan.changes {
        if let Change::CreateTable { table, def } = c {
            if def.rls_enabled {
                e.change(
                    &format!("enable row level security: {}", table.label()),
                    &[format!("ALTER TABLE {} ENABLE ROW LEVEL SECURITY;", table.sql())],
                    false,
                );
            }
            if def.rls_forced {
                e.change(
                    &format!("force row level security: {}", table.label()),
                    &[format!("ALTER TABLE {} FORCE ROW LEVEL SECURITY;", table.sql())],
                    false,
                );
            }
            for p in def.policies.values() {
                e.change(
                    &format!("create policy: {} on {}", p.name, table.label()),
                    &[policy_create_sql(table, p)],
                    false,
                );
            }
        }
    }
    for c in &plan.changes {
        match c {
            Change::EnableRls { table } => e.change(
                &format!("enable row level security: {}", table.label()),
                &[format!("ALTER TABLE {} ENABLE ROW LEVEL SECURITY;", table.sql())],
                false,
            ),
            Change::DisableRls { table } => e.change(
                &format!("disable row level security: {}", table.label()),
                &[format!("ALTER TABLE {} DISABLE ROW LEVEL SECURITY;", table.sql())],
                false,
            ),
            Change::ForceRls { table } => e.change(
                &format!("force row level security: {}", table.label()),
                &[format!("ALTER TABLE {} FORCE ROW LEVEL SECURITY;", table.sql())],
                false,
            ),
            Change::UnforceRls { table } => e.change(
                &format!("no force row level security: {}", table.label()),
                &[format!("ALTER TABLE {} NO FORCE ROW LEVEL SECURITY;", table.sql())],
                false,
            ),
            Change::CreatePolicy { table, def } => e.change(
                &format!("create policy: {} on {}", def.name, table.label()),
                &[policy_create_sql(table, def)],
                false,
            ),
            _ => {}
        }
    }

    // Phase 12: destructive drops of standalone objects.
    for c in &plan.changes {
        match c {
            Change::DropFunction {
                key,
                schema,
                signature,
                kind,
                replaced: false,
            } => e.change(
                &format!("drop {}: {key}", kind.label()),
                &[routine_drop_sql(*kind, schema, signature)],
                true,
            ),
            Change::DropSequence { seq } => e.change(
                &format!("drop sequence: {}", seq.label()),
                &[format!("DROP SEQUENCE IF EXISTS {};", seq.sql())],
                true,
            ),
            Change::DropEnum { ty } => e.change(
                &format!("drop enum: {}", ty.label()),
                &[format!("DROP TYPE IF EXISTS {};", ty.sql())],
                true,
            ),
            Change::DropExtension { name } => e.change(
                &format!("drop extension: {name}"),
                &[format!("DROP EXTENSION IF EXISTS {};", quote_ident(name))],
                true,
            ),
            _ => {}
        }
    }

    // Schemas drop LAST: enums/sequences/functions dropped above may live
    // inside them, and a plain (non-CASCADE) DROP SCHEMA requires the schema
    // to already be empty of dpm-scoped objects.
    for c in &plan.changes {
        if let Change::DropSchema { name } = c {
            e.change(
                &format!(
                    "drop schema: {name}\n\
                     Plain DROP (no CASCADE): fails if objects outside dpm's scope remain inside."
                ),
                &[format!("DROP SCHEMA IF EXISTS {};", quote_ident(name))],
                true,
            );
        }
    }

    e.line("COMMIT;");
    e.blank();
    finish(e)
}

fn finish(mut e: Emitter) -> Script {
    let _ = writeln!(
        e.out,
        "-- changes: {} total, {} destructive ({} gated), {} manual-review",
        e.change_count, e.destructive_count, e.gated_count, e.manual_count
    );
    Script {
        sql: e.out,
        change_count: e.change_count,
        destructive_count: e.destructive_count,
        gated_count: e.gated_count,
        manual_count: e.manual_count,
    }
}

fn emit_add_constraint(e: &mut Emitter, c: &Change) {
    if let Change::AddConstraint { table, name, def, kind, table_is_new } = c {
        // On existing tables, CHECK and FK adds use NOT VALID + VALIDATE so
        // the ACCESS EXCLUSIVE window stays short and existing rows are
        // validated without blocking writes.
        let two_step = !table_is_new && matches!(kind, ConstraintKind::Check | ConstraintKind::ForeignKey);
        let stmts = if two_step {
            vec![
                format!(
                    "ALTER TABLE {} ADD CONSTRAINT {} {def} NOT VALID;",
                    table.sql(),
                    quote_ident(name)
                ),
                format!("ALTER TABLE {} VALIDATE CONSTRAINT {};", table.sql(), quote_ident(name)),
            ]
        } else {
            vec![format!(
                "ALTER TABLE {} ADD CONSTRAINT {} {def};",
                table.sql(),
                quote_ident(name)
            )]
        };
        e.change(&format!("add constraint: {name} on {}", table.label()), &stmts, false);
    }
}

/// Column definition fragment used by CREATE TABLE and ADD COLUMN.
pub fn column_def_sql(col: &Column) -> String {
    column_def_sql_for_flavor(col, DatabaseFlavor::Postgres)
}

fn column_def_sql_for_flavor(col: &Column, database_flavor: DatabaseFlavor) -> String {
    let mut sql = format!("{} ", quote_ident(&col.name));
    if col.is_serial && col.identity.is_none() {
        sql.push_str(match col.type_sql.as_str() {
            "bigint" => "bigserial",
            "smallint" => "smallserial",
            _ => "serial",
        });
    } else {
        sql.push_str(&col.type_sql);
    }
    if let Some(collation) = &col.collation {
        let _ = write!(sql, " COLLATE {collation}");
    }
    if database_flavor == DatabaseFlavor::Cockroach && col.hidden {
        sql.push_str(" NOT VISIBLE");
    }
    if let Some(expr) = &col.generated {
        let _ = write!(sql, " GENERATED ALWAYS AS ({expr}) STORED");
    }
    if let Some(kind) = col.identity {
        let _ = write!(sql, " {}", kind.sql());
    }
    if col.not_null {
        sql.push_str(" NOT NULL");
    }
    if !col.is_serial && col.identity.is_none() && col.generated.is_none() {
        if let Some(expr) = &col.default {
            let _ = write!(sql, " DEFAULT {expr}");
        }
    }
    sql
}

/// CREATE TABLE with columns and all non-FK constraints inline; FKs are added
/// in the FK phase so cross-table ordering never matters.
fn create_table_sql(q: &QName, t: &Table, database_flavor: DatabaseFlavor) -> Vec<String> {
    let mut parts: Vec<String> = t
        .columns
        .iter()
        .map(|c| format!("  {}", column_def_sql_for_flavor(c, database_flavor)))
        .collect();
    for con in t.constraints.values() {
        if con.kind != ConstraintKind::ForeignKey {
            parts.push(format!("  CONSTRAINT {} {}", quote_ident(&con.name), con.def));
        }
    }
    let partition = t
        .partition_by
        .as_ref()
        .map(|p| format!("\nPARTITION BY {p}"))
        .unwrap_or_default();
    let mut stmts = vec![format!(
        "CREATE TABLE IF NOT EXISTS {} (\n{}\n){partition};",
        q.sql(),
        parts.join(",\n")
    )];
    for idx in t.indexes.values() {
        stmts.push(ensure_semicolon(&idx.def));
    }
    // FKs are deliberately NOT emitted here: they go in the global FK phase,
    // after every referenced table (and its PK/unique) exists, so table
    // creation order can never break a reference.
    stmts
}

fn sequence_create_sql(q: &QName, s: &Sequence) -> String {
    format!(
        "CREATE SEQUENCE IF NOT EXISTS {} AS {} INCREMENT BY {} MINVALUE {} MAXVALUE {} START WITH {} CACHE {}{};",
        q.sql(),
        s.type_sql,
        s.increment,
        s.min_value,
        s.max_value,
        s.start,
        s.cache,
        if s.cycle { " CYCLE" } else { " NO CYCLE" }
    )
}

fn sequence_alter_sql(q: &QName, s: &Sequence) -> Vec<String> {
    let regclass = q.sql().replace('\'', "''");
    vec![
        // No-op unless the current value violates the new bounds (in which
        // case the ALTER below would error); preserves is_called.
        format!(
            "SELECT setval('{regclass}', GREATEST(LEAST(last_value, {max}), {min}), is_called) FROM {seq};",
            max = s.max_value,
            min = s.min_value,
            seq = q.sql(),
        ),
        format!(
            "ALTER SEQUENCE {} AS {} INCREMENT BY {} MINVALUE {} MAXVALUE {} START WITH {} CACHE {}{};",
            q.sql(),
            s.type_sql,
            s.increment,
            s.min_value,
            s.max_value,
            s.start,
            s.cache,
            if s.cycle { " CYCLE" } else { " NO CYCLE" }
        ),
    ]
}

fn policy_create_sql(table: &QName, p: &Policy) -> String {
    let mut sql = format!(
        "CREATE POLICY {} ON {} AS {} FOR {}",
        quote_ident(&p.name),
        table.sql(),
        if p.permissive { "PERMISSIVE" } else { "RESTRICTIVE" },
        p.command
    );
    if !p.roles.is_empty() {
        let roles = p
            .roles
            .iter()
            .map(|r| if r == "public" { r.clone() } else { quote_ident(r) })
            .collect::<Vec<_>>()
            .join(", ");
        let _ = write!(sql, " TO {roles}");
    }
    if let Some(using) = &p.using_expr {
        let _ = write!(sql, " USING ({using})");
    }
    if let Some(check) = &p.check_expr {
        let _ = write!(sql, " WITH CHECK ({check})");
    }
    sql.push(';');
    sql
}

fn serial_sequence_qname(table: &QName, column: &str) -> QName {
    QName::new(table.schema.clone(), format!("{}_{}_seq", table.name, column))
}

fn replace_tag(replaced: bool) -> &'static str {
    if replaced {
        " (will be recreated below)"
    } else {
        ""
    }
}

fn ensure_semicolon(stmt: &str) -> String {
    let trimmed = stmt.trim_end();
    if trimmed.ends_with(';') {
        trimmed.to_string()
    } else {
        format!("{trimmed};")
    }
}

fn routine_create_sql(def: &str, replacing: bool) -> String {
    let trimmed = def.trim_start();
    let ddl = if replacing && !trimmed.starts_with("CREATE OR REPLACE ") {
        if let Some(rest) = trimmed.strip_prefix("CREATE FUNCTION ") {
            format!("CREATE OR REPLACE FUNCTION {rest}")
        } else if let Some(rest) = trimmed.strip_prefix("CREATE PROCEDURE ") {
            format!("CREATE OR REPLACE PROCEDURE {rest}")
        } else {
            trimmed.to_string()
        }
    } else {
        trimmed.to_string()
    };
    ensure_semicolon(&ddl)
}

fn routine_drop_sql(kind: RoutineKind, schema: &str, signature: &str) -> String {
    format!("DROP {} IF EXISTS {}.{signature};", kind.sql(), quote_ident(schema))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::diff::{diff, Change};

    fn base_column(name: &str, ty: &str) -> Column {
        Column {
            name: name.into(),
            type_sql: ty.into(),
            not_null: false,
            default: None,
            identity: None,
            generated: None,
            is_serial: false,
            collation: None,
            hidden: false,
        }
    }

    #[test]
    fn serial_column_renders_as_serial_keyword() {
        let mut c = base_column("id", "integer");
        c.is_serial = true;
        c.not_null = true;
        assert_eq!(column_def_sql(&c), "\"id\" serial NOT NULL");
        c.type_sql = "bigint".into();
        assert_eq!(column_def_sql(&c), "\"id\" bigserial NOT NULL");
    }

    #[test]
    fn identity_column_renders_generated_clause() {
        let mut c = base_column("id", "bigint");
        c.identity = Some(IdentityKind::Always);
        c.not_null = true;
        assert_eq!(column_def_sql(&c), "\"id\" bigint GENERATED ALWAYS AS IDENTITY NOT NULL");
    }

    #[test]
    fn cockroach_hidden_column_renders_not_visible() {
        let mut c = base_column("rowid", "bigint");
        c.hidden = true;
        c.not_null = true;
        c.default = Some("unique_rowid()".into());
        assert_eq!(
            column_def_sql_for_flavor(&c, DatabaseFlavor::Cockroach),
            "\"rowid\" bigint NOT VISIBLE NOT NULL DEFAULT unique_rowid()"
        );
        assert!(!column_def_sql(&c).contains("NOT VISIBLE"));
    }

    #[test]
    fn destructive_statements_are_gated_by_default() {
        let mut plan = crate::diff::Plan::default();
        plan.changes.push(Change::DropTable { table: QName::new("public", "gone") });
        let script = emit(&plan, &EmitOptions::default());
        assert!(script.sql.contains("-- DROP TABLE IF EXISTS \"public\".\"gone\";"));
        assert_eq!(script.gated_count, 1);

        let script = emit(&plan, &EmitOptions { allow_destructive: true, ..Default::default() });
        assert!(script.sql.contains("\nDROP TABLE IF EXISTS \"public\".\"gone\";"));
        assert_eq!(script.gated_count, 0);
    }

    #[test]
    fn enum_add_value_is_emitted_before_begin() {
        let mut plan = crate::diff::Plan::default();
        plan.changes.push(Change::AddEnumValue {
            ty: QName::new("public", "mood"),
            value: "elated".into(),
            before: None,
        });
        let script = emit(&plan, &EmitOptions::default());
        let add_pos = script.sql.find("ALTER TYPE").unwrap();
        let begin_pos = script.sql.find("BEGIN;").unwrap();
        assert!(add_pos < begin_pos, "enum ADD VALUE must precede BEGIN");
    }

    #[test]
    fn fk_adds_come_after_index_creates_and_pk_adds() {
        let mut plan = crate::diff::Plan::default();
        plan.changes.push(Change::AddConstraint {
            table: QName::new("public", "child"),
            name: "child_parent_fkey".into(),
            def: "FOREIGN KEY (parent_id) REFERENCES public.parent(id)".into(),
            kind: ConstraintKind::ForeignKey,
            table_is_new: false,
        });
        plan.changes.push(Change::AddConstraint {
            table: QName::new("public", "parent"),
            name: "parent_pkey".into(),
            def: "PRIMARY KEY (id)".into(),
            kind: ConstraintKind::PrimaryKey,
            table_is_new: false,
        });
        let script = emit(&plan, &EmitOptions::default());
        let pk = script.sql.find("parent_pkey").unwrap();
        let fk = script.sql.find("child_parent_fkey\" FOREIGN KEY").unwrap();
        assert!(pk < fk, "PK must be added before FK");
        assert!(script.sql.contains("NOT VALID"), "FK on existing table uses NOT VALID");
        assert!(script.sql.contains("VALIDATE CONSTRAINT"));
    }

    #[test]
    fn empty_plan_emits_no_diff_note() {
        let a = Catalog::empty_with_schemas(["public".into()]);
        let plan = diff(&a, &a.clone());
        let script = emit(&plan, &EmitOptions::default());
        assert!(script.sql.contains("No schema differences detected"));
        assert!(!script.sql.contains("BEGIN;"));
    }
}

#[cfg(test)]
mod ordering_tests {
    use super::*;
    use crate::diff::{diff, Change, Plan};
    use std::collections::BTreeMap;

    fn plan_of(changes: Vec<Change>) -> Plan {
        Plan { changes }
    }

    fn pos(hay: &str, needle: &str) -> usize {
        hay.find(needle).unwrap_or_else(|| panic!("missing {needle:?} in:\n{hay}"))
    }

    #[test]
    fn drops_precede_creates_and_fk_drops_come_first() {
        let t = QName::new("public", "t");
        let plan = plan_of(vec![
            Change::CreateIndex { table: t.clone(), name: "t_idx".into(), def: "CREATE INDEX t_idx ON public.t USING btree (a)".into() },
            Change::DropIndex { index: QName::new("public", "t_idx"), unique: false, replaced: true },
            Change::AddConstraint { table: t.clone(), name: "t_chk".into(), def: "CHECK ((a > 0))".into(), kind: ConstraintKind::Check, table_is_new: false },
            Change::DropConstraint { table: t.clone(), name: "t_chk".into(), kind: ConstraintKind::Check, replaced: true },
            Change::DropConstraint { table: t.clone(), name: "t_fk".into(), kind: ConstraintKind::ForeignKey, replaced: true },
            Change::AddConstraint { table: t.clone(), name: "t_fk".into(), def: "FOREIGN KEY (a) REFERENCES public.p(id)".into(), kind: ConstraintKind::ForeignKey, table_is_new: false },
        ]);
        let sql = emit(&plan, &EmitOptions { allow_destructive: true, ..Default::default() }).sql;

        // FK drop before non-FK drop; all drops before any (re)creates.
        assert!(pos(&sql, "DROP CONSTRAINT IF EXISTS \"t_fk\"") < pos(&sql, "DROP CONSTRAINT IF EXISTS \"t_chk\""));
        assert!(pos(&sql, "DROP CONSTRAINT IF EXISTS \"t_chk\"") < pos(&sql, "ADD CONSTRAINT \"t_chk\""));
        assert!(pos(&sql, "DROP INDEX IF EXISTS") < pos(&sql, "CREATE INDEX t_idx"));
        // FK re-add comes after non-FK re-add and after index create.
        assert!(pos(&sql, "ADD CONSTRAINT \"t_chk\"") < pos(&sql, "ADD CONSTRAINT \"t_fk\""));
        assert!(pos(&sql, "CREATE INDEX t_idx") < pos(&sql, "ADD CONSTRAINT \"t_fk\""));
    }

    #[test]
    fn cockroach_unique_constraint_drops_use_the_index_ddl() {
        let plan = plan_of(vec![Change::DropConstraint {
            table: QName::new("app", "users"),
            name: "users_email_key".into(),
            kind: ConstraintKind::Unique,
            replaced: false,
        }]);

        let postgres = emit(
            &plan,
            &EmitOptions {
                allow_destructive: true,
                ..Default::default()
            },
        )
        .sql;
        assert!(postgres.contains(
            "ALTER TABLE \"app\".\"users\" DROP CONSTRAINT IF EXISTS \"users_email_key\";"
        ));

        let cockroach = emit(
            &plan,
            &EmitOptions {
                allow_destructive: true,
                database_flavor: DatabaseFlavor::Cockroach,
                ..Default::default()
            },
        )
        .sql;
        assert!(cockroach.contains(
            "DROP INDEX IF EXISTS \"app\".\"users_email_key\" CASCADE;"
        ));
        assert!(!cockroach.contains("DROP CONSTRAINT"));
    }

    #[test]
    fn changed_trigger_drops_before_function_replace_and_recreates_after() {
        let t = QName::new("public", "ev");
        let plan = plan_of(vec![
            Change::CreateFunction { key: "public.bump()".into(), kind: RoutineKind::Function, def: "CREATE OR REPLACE FUNCTION public.bump() ...".into(), replacing: true },
            Change::CreateTrigger { key: "public.ev.trg".into(), table: t.clone(), def: "CREATE TRIGGER trg BEFORE UPDATE ON public.ev ...".into() },
            Change::DropTrigger { table: t.clone(), name: "trg".into(), replaced: true },
        ]);
        let sql = emit(&plan, &EmitOptions::default()).sql;
        assert!(pos(&sql, "DROP TRIGGER IF EXISTS \"trg\"") < pos(&sql, "CREATE OR REPLACE FUNCTION"));
        assert!(pos(&sql, "CREATE OR REPLACE FUNCTION") < pos(&sql, "CREATE TRIGGER trg"));
    }

    #[test]
    fn drop_schema_renders_gated_and_without_cascade() {
        let plan = plan_of(vec![Change::DropSchema { name: "app".into() }]);
        let script = emit(&plan, &EmitOptions::default());
        assert_eq!(script.gated_count, 1);
        assert!(script.sql.contains("-- DROP SCHEMA IF EXISTS \"app\";"));
        assert!(!script.sql.contains("DROP SCHEMA IF EXISTS \"app\" CASCADE"));

        let live = emit(&plan, &EmitOptions { allow_destructive: true, ..Default::default() });
        assert!(live.sql.contains("\nDROP SCHEMA IF EXISTS \"app\";"));
    }

    #[test]
    fn alter_sequence_clamps_counter_before_altering() {
        let seq = QName::new("public", "order_numbers");
        let def = Sequence { type_sql: "bigint".into(), start: 100, increment: 10, min_value: 100, max_value: 999, cache: 5, cycle: true };
        let plan = plan_of(vec![Change::AlterSequence { seq, def }]);
        let sql = emit(&plan, &EmitOptions::default()).sql;
        let clamp = pos(&sql, "SELECT setval(");
        let alter = pos(&sql, "ALTER SEQUENCE");
        assert!(clamp < alter, "clamp must precede the ALTER");
        assert!(sql.contains("GREATEST(LEAST(last_value, 999), 100)"));
        assert!(sql.contains("MINVALUE 100 MAXVALUE 999"));
        assert!(sql.contains(" CYCLE"));
    }

    #[test]
    fn make_serial_emits_sequence_default_ownership_and_setval() {
        let plan = plan_of(vec![Change::MakeSerial { table: QName::new("public", "a"), column: "id".into(), type_sql: "integer".into() }]);
        let sql = emit(&plan, &EmitOptions::default()).sql;
        assert!(sql.contains("CREATE SEQUENCE IF NOT EXISTS \"public\".\"a_id_seq\""));
        assert!(sql.contains("SET DEFAULT nextval"));
        assert!(sql.contains("OWNED BY \"public\".\"a\".\"id\""));
        assert!(sql.contains("setval"));
    }

    #[test]
    fn policy_sql_covers_restrictive_roles_and_checks() {
        let p = Policy {
            name: "docs_write".into(),
            permissive: false,
            command: "UPDATE".into(),
            roles: vec!["public".into(), "app_user".into()],
            using_expr: Some("open".into()),
            check_expr: Some("open AND NOT locked".into()),
        };
        let sql = policy_create_sql(&QName::new("public", "docs"), &p);
        assert_eq!(
            sql,
            "CREATE POLICY \"docs_write\" ON \"public\".\"docs\" AS RESTRICTIVE FOR UPDATE TO public, \"app_user\" USING (open) WITH CHECK (open AND NOT locked);"
        );
    }

    #[test]
    fn regenerate_column_is_destructive_and_pairs_drop_add() {
        let col = Column {
            name: "title_len".into(),
            type_sql: "integer".into(),
            not_null: false,
            default: None,
            identity: None,
            generated: Some("length(title)".into()),
            is_serial: false,
            collation: None,
            hidden: false,
        };
        let plan = plan_of(vec![Change::RegenerateColumn { table: QName::new("public", "posts"), def: col }]);
        let script = emit(&plan, &EmitOptions { allow_destructive: true, ..Default::default() });
        assert_eq!(script.destructive_count, 1);
        let sql = script.sql;
        assert!(pos(&sql, "DROP COLUMN IF EXISTS \"title_len\"") < pos(&sql, "ADD COLUMN \"title_len\" integer GENERATED ALWAYS AS (length(title)) STORED"));
    }

    #[test]
    fn create_table_inlines_non_fk_constraints_and_defers_fks() {
        let mut constraints = BTreeMap::new();
        constraints.insert("c_pkey".into(), Constraint { name: "c_pkey".into(), kind: ConstraintKind::PrimaryKey, def: "PRIMARY KEY (id)".into() });
        constraints.insert("c_fk".into(), Constraint { name: "c_fk".into(), kind: ConstraintKind::ForeignKey, def: "FOREIGN KEY (p) REFERENCES public.p(id)".into() });
        let table = Table {
            columns: vec![Column { name: "id".into(), type_sql: "bigint".into(), not_null: true, default: None, identity: None, generated: None, is_serial: false, collation: None, hidden: false }],
            constraints,
            indexes: BTreeMap::new(),
            partition_by: None,
            rls_enabled: false,
            rls_forced: false,
            policies: BTreeMap::new(),
        };
        let plan = plan_of(vec![Change::CreateTable { table: QName::new("public", "c"), def: table }]);
        let sql = emit(&plan, &EmitOptions::default()).sql;
        let create = pos(&sql, "CREATE TABLE IF NOT EXISTS \"public\".\"c\"");
        let fk = pos(&sql, "ADD CONSTRAINT \"c_fk\"");
        assert!(sql[create..fk].contains("CONSTRAINT \"c_pkey\" PRIMARY KEY (id)"), "PK inline in CREATE TABLE");
        assert!(!sql[create..fk].contains("c_fk\" FOREIGN KEY") || fk > create, "FK deferred to FK phase");
        // FK on a brand-new (empty) table is single-step: no NOT VALID.
        assert!(!sql.contains("\"c_fk\" FOREIGN KEY (p) REFERENCES public.p(id) NOT VALID"));
    }

    #[test]
    fn empty_diff_of_identical_synthetic_catalogs_is_stable() {
        let cat = Catalog::empty_with_schemas(["public".into()]);
        let script = emit(&diff(&cat, &cat.clone()), &EmitOptions::default());
        assert_eq!(script.change_count, 0);
        assert_eq!(script.destructive_count, 0);
    }
}
