//! The catalog model: a normalized, serializable snapshot of everything dpm
//! diffs. Both sides of a diff are represented this way regardless of origin
//! (live database, saved JSON dump, or a .sql file materialized in a shadow
//! database), so the diff engine never needs to know where a schema came from.
//!
//! Deparsed definition strings (`pg_get_constraintdef`, `pg_get_indexdef`,
//! `pg_get_viewdef`, `pg_get_functiondef`, `pg_get_triggerdef`, `format_type`)
//! are stored verbatim. Because both catalogs are introspected with
//! `search_path = ''`, Postgres prints both sides in the same canonical,
//! fully-qualified form and equality is plain string comparison — no
//! normalization heuristics.

use std::collections::{BTreeMap, BTreeSet};

use serde::{Deserialize, Serialize};

pub const CATALOG_FORMAT_VERSION: u32 = 1;

/// The server family that produced a catalog.  CockroachDB speaks the
/// PostgreSQL wire protocol, but its catalog and DDL capabilities are not a
/// byte-for-byte PostgreSQL implementation.  Keeping this on the snapshot
/// prevents migrations from silently mixing the two dialects.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DatabaseFlavor {
    #[default]
    Postgres,
    Cockroach,
}

impl DatabaseFlavor {
    pub fn label(self) -> &'static str {
        match self {
            Self::Postgres => "PostgreSQL",
            Self::Cockroach => "CockroachDB",
        }
    }
}

/// Schema-qualified object name. Ordered so BTreeMap iteration (and therefore
/// emitted SQL) is deterministic.
///
/// Serialized (including as JSON map keys) in canonical SQL-quoted form —
/// `"schema"."name"` — which is unambiguous even for identifiers containing
/// dots or quotes.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct QName {
    pub schema: String,
    pub name: String,
}

impl Serialize for QName {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(&self.sql())
    }
}

impl<'de> Deserialize<'de> for QName {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = String::deserialize(deserializer)?;
        parse_qname(&raw).ok_or_else(|| serde::de::Error::custom(format!("invalid qualified name: {raw:?}")))
    }
}

/// Parse the canonical `"schema"."name"` form (with `""` quote escapes).
pub fn parse_qname(raw: &str) -> Option<QName> {
    fn take_quoted(s: &str) -> Option<(String, &str)> {
        let rest = s.strip_prefix('"')?;
        let mut out = String::new();
        let mut chars = rest.char_indices();
        while let Some((i, ch)) = chars.next() {
            if ch == '"' {
                if rest[i + 1..].starts_with('"') {
                    out.push('"');
                    chars.next();
                } else {
                    return Some((out, &rest[i + 1..]));
                }
            } else {
                out.push(ch);
            }
        }
        None
    }
    let (schema, rest) = take_quoted(raw)?;
    let rest = rest.strip_prefix('.')?;
    let (name, rest) = take_quoted(rest)?;
    rest.is_empty().then_some(QName { schema, name })
}

impl QName {
    pub fn new(schema: impl Into<String>, name: impl Into<String>) -> Self {
        Self { schema: schema.into(), name: name.into() }
    }

    /// Quoted, schema-qualified identifier for emitted DDL.
    pub fn sql(&self) -> String {
        format!("{}.{}", quote_ident(&self.schema), quote_ident(&self.name))
    }

    /// Human-readable label for comments and logs.
    pub fn label(&self) -> String {
        format!("{}.{}", self.schema, self.name)
    }
}

/// Double-quote an identifier, escaping embedded quotes.
pub fn quote_ident(ident: &str) -> String {
    format!("\"{}\"", ident.replace('"', "\"\""))
}

/// Single-quote a string literal, escaping embedded quotes.
pub fn quote_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum IdentityKind {
    Always,
    ByDefault,
}

impl IdentityKind {
    pub fn sql(self) -> &'static str {
        match self {
            IdentityKind::Always => "GENERATED ALWAYS AS IDENTITY",
            IdentityKind::ByDefault => "GENERATED BY DEFAULT AS IDENTITY",
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Column {
    pub name: String,
    /// Canonical type from `format_type(atttypid, atttypmod)` with
    /// `search_path = ''` (e.g. `integer`, `character varying(255)`,
    /// `public.mood`, `numeric(10,2)[]`).
    pub type_sql: String,
    pub not_null: bool,
    /// Deparsed default expression. `None` for generated and serial columns
    /// (see `generated` / `is_serial`).
    pub default: Option<String>,
    pub identity: Option<IdentityKind>,
    /// Generation expression for `GENERATED ALWAYS AS (...) STORED` columns.
    pub generated: Option<String>,
    /// True when the column is backed by an owned sequence via a
    /// `nextval(...)` default (classic `serial`/`bigserial`). The sequence
    /// name is intentionally not part of equality: two databases converged
    /// via `serial` may have differently-named sequences only when tables
    /// were renamed, which dpm does not track.
    pub is_serial: bool,
    /// Non-default collation, schema-qualified (e.g. `pg_catalog."C"`).
    pub collation: Option<String>,
    /// CockroachDB column visibility.  Its implicit primary-key `rowid` is
    /// hidden, and user columns may be declared `NOT VISIBLE`. PostgreSQL
    /// catalogs deserialize this as `false`.
    #[serde(default)]
    pub hidden: bool,
}

impl Column {
    /// The facets that participate in column equality. Serial columns compare
    /// equal regardless of the underlying sequence name.
    pub fn semantic_eq(&self, other: &Column) -> bool {
        self.type_sql == other.type_sql
            && self.not_null == other.not_null
            && self.identity == other.identity
            && self.generated == other.generated
            && self.is_serial == other.is_serial
            && self.collation == other.collation
            && self.hidden == other.hidden
            && (self.is_serial || self.default == other.default)
    }
}

/// Constraint kinds mirror `pg_constraint.contype`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum ConstraintKind {
    PrimaryKey,
    Unique,
    Check,
    ForeignKey,
    Exclusion,
}

impl ConstraintKind {
    pub fn from_contype(c: &str) -> Option<Self> {
        match c {
            "p" => Some(Self::PrimaryKey),
            "u" => Some(Self::Unique),
            "c" => Some(Self::Check),
            "f" => Some(Self::ForeignKey),
            "x" => Some(Self::Exclusion),
            _ => None,
        }
    }

    /// Dropping one of these weakens integrity that may not be restorable
    /// (duplicates can slip in before a re-add), so pure removals are gated.
    pub fn drop_is_destructive(self) -> bool {
        matches!(self, Self::PrimaryKey | Self::Unique | Self::Exclusion)
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Constraint {
    pub name: String,
    pub kind: ConstraintKind,
    /// Full `pg_get_constraintdef(oid)` text, e.g.
    /// `FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE`.
    pub def: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Index {
    pub name: String,
    /// Full `pg_get_indexdef(indexrelid)` text (a complete CREATE INDEX
    /// statement, including the index name and USING clause).
    pub def: String,
    pub unique: bool,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Policy {
    pub name: String,
    pub permissive: bool,
    /// Command the policy applies to: ALL | SELECT | INSERT | UPDATE | DELETE.
    pub command: String,
    /// Role names the policy applies to (`{public}` when unrestricted).
    pub roles: Vec<String>,
    /// Deparsed USING expression.
    pub using_expr: Option<String>,
    /// Deparsed WITH CHECK expression.
    pub check_expr: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Table {
    /// Columns in ordinal order. Order matters for CREATE TABLE emission but
    /// deliberately not for equality (converged databases may disagree on
    /// ordinals after historic ADD COLUMNs).
    pub columns: Vec<Column>,
    pub constraints: BTreeMap<String, Constraint>,
    pub indexes: BTreeMap<String, Index>,
    /// `pg_get_partkeydef` for partitioned tables (`PARTITION BY ...`).
    pub partition_by: Option<String>,
    pub rls_enabled: bool,
    pub rls_forced: bool,
    pub policies: BTreeMap<String, Policy>,
}

impl Table {
    pub fn column(&self, name: &str) -> Option<&Column> {
        self.columns.iter().find(|c| c.name == name)
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct View {
    pub materialized: bool,
    /// `pg_get_viewdef(oid, true)` body (no CREATE prefix).
    pub def: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Sequence {
    pub type_sql: String,
    pub start: i64,
    pub increment: i64,
    pub min_value: i64,
    pub max_value: i64,
    pub cache: i64,
    pub cycle: bool,
}

/// The two routine kinds managed through `pg_proc`.  Keeping the kind in the
/// catalog matters at drop time: PostgreSQL and CockroachDB both require
/// `DROP PROCEDURE` for procedures rather than accepting `DROP FUNCTION`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RoutineKind {
    #[default]
    Function,
    Procedure,
}

impl RoutineKind {
    pub fn from_prokind(value: &str) -> Option<Self> {
        match value {
            "f" => Some(Self::Function),
            "p" => Some(Self::Procedure),
            _ => None,
        }
    }

    pub fn sql(self) -> &'static str {
        match self {
            Self::Function => "FUNCTION",
            Self::Procedure => "PROCEDURE",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::Function => "function",
            Self::Procedure => "procedure",
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Function {
    /// `name(identity args)` — uniquely identifies an overload within a schema.
    pub signature: String,
    /// Raw routine name and canonical identity arguments are stored
    /// separately so DROP statements can quote hostile identifiers safely.
    /// Legacy catalogs fall back to their historical `signature` field.
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub identity_arguments: String,
    /// Old catalog JSON predates procedure-aware drops and therefore
    /// deserializes as a function.
    #[serde(default)]
    pub kind: RoutineKind,
    /// Full `pg_get_functiondef(oid)` text (a complete
    /// `CREATE OR REPLACE FUNCTION|PROCEDURE ...` statement).
    pub def: String,
}

impl Function {
    pub fn drop_signature_sql(&self) -> String {
        if self.name.is_empty() {
            self.signature.clone()
        } else {
            format!(
                "{}({})",
                quote_ident(&self.name),
                self.identity_arguments
            )
        }
    }
}

/// Trigger firing mode. CockroachDB exposes the `Origin`/`Disabled` subset;
/// PostgreSQL additionally supports replica-only and always-fire modes.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TriggerMode {
    #[default]
    Origin,
    Disabled,
    Replica,
    Always,
}

impl TriggerMode {
    pub fn from_postgres(value: &str) -> Option<Self> {
        match value {
            "O" => Some(Self::Origin),
            "D" => Some(Self::Disabled),
            "R" => Some(Self::Replica),
            "A" => Some(Self::Always),
            _ => None,
        }
    }

    pub fn alter_sql(self) -> &'static str {
        match self {
            Self::Origin => "ENABLE TRIGGER",
            Self::Disabled => "DISABLE TRIGGER",
            Self::Replica => "ENABLE REPLICA TRIGGER",
            Self::Always => "ENABLE ALWAYS TRIGGER",
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Trigger {
    pub table: QName,
    pub name: String,
    /// Old catalog JSON predates trigger-state introspection and defaults to
    /// the normal enabled/origin mode.
    #[serde(default)]
    pub mode: TriggerMode,
    /// Full `pg_get_triggerdef(oid)` text (a complete CREATE TRIGGER statement).
    pub def: String,
}

/// A complete snapshot of the diffable surface of one database, restricted to
/// a set of schemas.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Catalog {
    #[serde(default = "default_format_version")]
    pub format_version: u32,
    /// `server_version_num` at introspection time; 0 for synthetic catalogs.
    #[serde(default)]
    pub server_version_num: i32,
    /// Server family at introspection time.  Old catalog dumps predate this
    /// field and intentionally deserialize as PostgreSQL for compatibility.
    #[serde(default)]
    pub database_flavor: DatabaseFlavor,
    /// The schemas this snapshot covers (diff scope).
    pub schemas: BTreeSet<String>,
    pub extensions: BTreeSet<String>,
    /// Enum name -> ordered labels.
    pub enums: BTreeMap<QName, Vec<String>>,
    /// Standalone sequences only — sequences owned by serial/identity columns
    /// are represented by their column and excluded here.
    pub sequences: BTreeMap<QName, Sequence>,
    pub tables: BTreeMap<QName, Table>,
    pub views: BTreeMap<QName, View>,
    /// Key: `schema.name(identity args)`.
    pub functions: BTreeMap<String, Function>,
    /// Key: `schema.table.trigger_name`.
    pub triggers: BTreeMap<String, Trigger>,
}

fn default_format_version() -> u32 {
    CATALOG_FORMAT_VERSION
}

impl Catalog {
    pub fn empty_with_schemas(schemas: impl IntoIterator<Item = String>) -> Self {
        Self {
            format_version: CATALOG_FORMAT_VERSION,
            schemas: schemas.into_iter().collect(),
            ..Self::default()
        }
    }

    pub fn object_count(&self) -> usize {
        self.enums.len()
            + self.sequences.len()
            + self.tables.len()
            + self.views.len()
            + self.functions.len()
            + self.triggers.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quote_ident_escapes_quotes() {
        assert_eq!(quote_ident("plain"), "\"plain\"");
        assert_eq!(quote_ident("we\"ird"), "\"we\"\"ird\"");
    }

    #[test]
    fn quote_literal_escapes_quotes() {
        assert_eq!(quote_literal("it's"), "'it''s'");
    }

    #[test]
    fn legacy_routine_json_defaults_to_function() {
        let routine: Function = serde_json::from_str(
            r#"{"signature":"f(integer)","def":"CREATE FUNCTION f(integer) RETURNS integer LANGUAGE SQL AS 'SELECT 1'"}"#,
        )
        .unwrap();
        assert_eq!(routine.kind, RoutineKind::Function);
        assert_eq!(routine.drop_signature_sql(), "f(integer)");
    }

    #[test]
    fn routine_drop_signature_quotes_hostile_name() {
        let routine = Function {
            signature: "do work(integer)".into(),
            name: "do work".into(),
            identity_arguments: "integer".into(),
            kind: RoutineKind::Procedure,
            def: String::new(),
        };
        assert_eq!(routine.drop_signature_sql(), "\"do work\"(integer)");
    }

    #[test]
    fn legacy_trigger_json_defaults_to_enabled_origin_mode() {
        let trigger: Trigger = serde_json::from_str(
            r#"{"table":"\"public\".\"t\"","name":"trg","def":"CREATE TRIGGER trg BEFORE INSERT ON public.t EXECUTE FUNCTION public.f()"}"#,
        )
        .unwrap();
        assert_eq!(trigger.mode, TriggerMode::Origin);
    }

    #[test]
    fn serial_columns_ignore_default_text() {
        let a = Column {
            name: "id".into(),
            type_sql: "integer".into(),
            not_null: true,
            default: Some("nextval('public.t_id_seq'::regclass)".into()),
            identity: None,
            generated: None,
            is_serial: true,
            collation: None,
            hidden: false,
        };
        let mut b = a.clone();
        b.default = Some("nextval('public.renamed_seq'::regclass)".into());
        assert!(a.semantic_eq(&b));
        b.is_serial = false;
        assert!(!a.semantic_eq(&b));
    }

    #[test]
    fn catalog_json_round_trip() {
        let mut cat = Catalog::empty_with_schemas(["public".to_string()]);
        cat.enums.insert(QName::new("public", "mood"), vec!["sad".into(), "ok".into()]);
        let json = serde_json::to_string(&cat).unwrap();
        let back: Catalog = serde_json::from_str(&json).unwrap();
        assert_eq!(cat, back);
    }

    #[test]
    fn legacy_column_json_defaults_to_visible() {
        let json = serde_json::json!({
            "name": "id",
            "type_sql": "bigint",
            "not_null": true,
            "default": null,
            "identity": null,
            "generated": null,
            "is_serial": false,
            "collation": null
        });
        let column: Column = serde_json::from_value(json).unwrap();
        assert!(!column.hidden);
    }

    #[test]
    fn qname_round_trips_hostile_identifiers() {
        for (schema, name) in [
            ("public", "users"),
            ("we.ird", "na\"me"),
            ("a\".\"b", "c.d"),
        ] {
            let q = QName::new(schema, name);
            let encoded = serde_json::to_string(&q).unwrap();
            let back: QName = serde_json::from_str(&encoded).unwrap();
            assert_eq!(q, back, "encoded: {encoded}");
        }
    }
}
